// Ejercicios del Tema 1 rescatados de la guía antigua.
//
// Estaban en page.tsx, dentro de una pantalla que dejó de tener entrada en el
// menú al unificar el Tema 1 como capítulo 1: quedaron inaccesibles y fuera
// del repaso espaciado. Se migran aquí para devolverlos al circuito.
//
// Van en un fichero aparte a propósito. El banco curado de bio-question-bank.ts
// garantiza que cada distractor lleva su explicación, y estos no la traen: no
// existía en el formato original. Mantenerlos separados conserva esa garantía
// y deja la deuda a la vista en lugar de disolverla.

import type { BankQuestion } from "./bio-question-bank";

/** Migrados sin explicación por opción. Escribirlas es trabajo pendiente. */
export const legacyTema1Questions: BankQuestion[] = [
  {
    id: "legacy-t1-1",
    themeId: "tema-1-carbono",
    type: "choice",
    prompt: "En CH₂=CH₂, ¿cuántos pares de electrones comparten los dos carbonos?",
    options: ["1 par", "2 pares", "4 pares"],
    correctAnswer: "2 pares",
    explanation: "El signo = representa dos enlaces: son 2 pares, es decir, 4 electrones compartidos.",
    hint: "Vuelve a la cuenta hasta cuatro y comprueba qué valencias quedan libres.",
    difficulty: 1,
    tags: ["detective-de-enlaces"],
  },
  {
    id: "legacy-t1-2",
    themeId: "tema-1-carbono",
    type: "choice",
    prompt: "¿Cuántos enlaces suma el carbono central de CH₃—CH=CH₂?",
    options: ["3", "4", "5"],
    correctAnswer: "4",
    explanation: "Suma 1 con H + 1 con el C izquierdo + 2 con el C derecho = 4.",
    hint: "Vuelve a la cuenta hasta cuatro y comprueba qué valencias quedan libres.",
    difficulty: 1,
    tags: ["detective-de-enlaces"],
  },
  {
    id: "legacy-t1-3",
    themeId: "tema-1-carbono",
    type: "choice",
    prompt: "Dos carbonos están unidos por un triple enlace. ¿Cuántos H lleva cada uno?",
    options: ["1", "2", "3"],
    correctAnswer: "1",
    explanation: "El triple enlace ya ocupa 3 de los 4 enlaces de cada carbono: solo queda sitio para 1 H.",
    hint: "Vuelve a la cuenta hasta cuatro y comprueba qué valencias quedan libres.",
    difficulty: 2,
    tags: ["completa-los-hidrogenos"],
  },
  {
    id: "legacy-t1-4",
    themeId: "tema-1-carbono",
    type: "choice",
    prompt: "Completa el extremo: CH₃—CH₂—C___",
    options: ["H", "H₂", "H₃"],
    correctAnswer: "H₃",
    explanation: "El carbono final solo usa un enlace con la cadena; necesita tres enlaces C—H.",
    hint: "Vuelve a la cuenta hasta cuatro y comprueba qué valencias quedan libres.",
    difficulty: 2,
    tags: ["completa-los-hidrogenos"],
  },
  {
    id: "legacy-t1-5",
    themeId: "tema-1-carbono",
    type: "choice",
    prompt: "¿Qué estructura corresponde al eteno?",
    options: ["CH₃—CH₃", "CH₂=CH₂", "HC≡CH"],
    correctAnswer: "CH₂=CH₂",
    explanation: "El sufijo -eno indica doble enlace; cada C conserva dos enlaces para H.",
    hint: "Vuelve a la cuenta hasta cuatro y comprueba qué valencias quedan libres.",
    difficulty: 3,
    tags: ["constructor-molecular"],
  },
  {
    id: "legacy-t1-6",
    themeId: "tema-1-carbono",
    type: "choice",
    prompt: "¿Cuál es la fórmula molecular de CH₃—CH₂—OH?",
    options: ["C₂H₅O", "C₂H₆O", "CH₃O"],
    correctAnswer: "C₂H₆O",
    explanation: "Cuenta todos los átomos: 2 C, 6 H y 1 O. Resultado: C₂H₆O.",
    hint: "Vuelve a la cuenta hasta cuatro y comprueba qué valencias quedan libres.",
    difficulty: 3,
    tags: ["traductor-de-formulas"],
  },
  {
    id: "legacy-t1-7",
    themeId: "tema-1-carbono",
    type: "choice",
    prompt: "¿Qué tipo de representación es CH₃—CH₃?",
    options: ["Molecular", "Semidesarrollada", "Empírica"],
    correctAnswer: "Semidesarrollada",
    explanation: "Agrupa los H con cada carbono pero muestra el enlace C—C: es semidesarrollada.",
    hint: "Vuelve a la cuenta hasta cuatro y comprueba qué valencias quedan libres.",
    difficulty: 3,
    tags: ["traductor-de-formulas"],
  },
  {
    id: "legacy-t1-8",
    themeId: "tema-1-carbono",
    type: "choice",
    prompt: "En CH₃—CH₂—CH₃, ¿qué tipo de carbono es el central?",
    options: ["Primario", "Secundario", "Terciario"],
    correctAnswer: "Secundario",
    explanation: "Está unido directamente a dos carbonos; por eso es secundario.",
    hint: "Vuelve a la cuenta hasta cuatro y comprueba qué valencias quedan libres.",
    difficulty: 3,
    tags: ["detective-de-carbonos"],
  },
  {
    id: "legacy-t1-9",
    themeId: "tema-1-carbono",
    type: "choice",
    prompt: "Un carbono unido directamente a cuatro carbonos se llama…",
    options: ["Tetravalente", "Cuaternario", "Carbono 4"],
    correctAnswer: "Cuaternario",
    explanation: "Cuaternario describe cuatro vecinos carbono. Tetravalente describe una capacidad total de cuatro enlaces.",
    hint: "Vuelve a la cuenta hasta cuatro y comprueba qué valencias quedan libres.",
    difficulty: 3,
    tags: ["detective-de-carbonos"],
  },
  {
    id: "legacy-t1-10",
    themeId: "tema-1-carbono",
    type: "choice",
    prompt: "¿Qué grupo funcional caracteriza a un ácido graso?",
    options: ["Amina", "Carboxilo", "Éter"],
    correctAnswer: "Carboxilo",
    explanation: "Los ácidos grasos poseen una cadena hidrocarbonada y un grupo carboxilo —COOH.",
    hint: "Vuelve a la cuenta hasta cuatro y comprueba qué valencias quedan libres.",
    difficulty: 3,
    tags: ["bioquimica"],
  },
  {
    id: "legacy-t1-11",
    themeId: "tema-1-carbono",
    type: "choice",
    prompt: "El enlace que une aminoácidos es químicamente una…",
    options: ["Amida", "Cetona", "Amina"],
    correctAnswer: "Amida",
    explanation: "El enlace peptídico contiene —C(=O)—N—, la estructura característica de una amida.",
    hint: "Vuelve a la cuenta hasta cuatro y comprueba qué valencias quedan libres.",
    difficulty: 3,
    tags: ["bioquimica"],
  },
  {
    id: "legacy-t1-12",
    themeId: "tema-1-carbono",
    type: "choice",
    prompt: "En but-2-eno, ¿qué señala el número 2?",
    options: ["Que hay dos carbonos", "Que C=C comienza en C2", "Que existen dos dobles enlaces"],
    correctAnswer: "Que C=C comienza en C2",
    explanation: "El localizador no cuenta elementos: indica que el doble enlace comienza en el carbono 2.",
    hint: "Vuelve a la cuenta hasta cuatro y comprueba qué valencias quedan libres.",
    difficulty: 3,
    tags: ["lee-el-localizador"],
  },
  {
    id: "legacy-t1-13",
    themeId: "tema-1-carbono",
    type: "choice",
    prompt: "En 2-metilbutano, ¿qué significa metil?",
    options: ["La cadena principal", "Una rama —CH₃", "Un enlace doble"],
    correctAnswer: "Una rama —CH₃",
    explanation: "Metil es el sustituyente —CH₃ que queda como rama de la cadena principal de cuatro carbonos.",
    hint: "Vuelve a la cuenta hasta cuatro y comprueba qué valencias quedan libres.",
    difficulty: 3,
    tags: ["encuentra-la-rama"],
  },
  {
    id: "legacy-t1-14",
    themeId: "tema-1-carbono",
    type: "choice",
    prompt: "¿Qué informa el nombre 2,3-dimetilbutano?",
    options: ["Dos metilos en C2 y C3", "Tres metilos en C2", "Un metilo y dos dobles enlaces"],
    correctAnswer: "Dos metilos en C2 y C3",
    explanation: "di- indica dos ramas metil; los localizadores 2,3 señalan la posición de cada una.",
    hint: "Vuelve a la cuenta hasta cuatro y comprueba qué valencias quedan libres.",
    difficulty: 3,
    tags: ["multiplicadores"],
  },
  {
    id: "legacy-t1-15",
    themeId: "tema-1-carbono",
    type: "choice",
    prompt: "¿Qué grupo permite reconocer el glicerol como alcohol?",
    options: ["—OH", "—COOH", "—NH₂"],
    correctAnswer: "—OH",
    explanation: "El glicerol posee tres grupos hidroxilo —OH; por eso es un triol.",
    hint: "Vuelve a la cuenta hasta cuatro y comprueba qué valencias quedan libres.",
    difficulty: 3,
    tags: ["alcoholes-en-nutricion"],
  },
  {
    id: "legacy-t1-16",
    themeId: "tema-1-carbono",
    type: "choice",
    prompt: "¿Qué dos zonas distingues en un ácido graso?",
    options: ["Amina y alcohol", "Cadena hidrocarbonada y carboxilo", "Cetona y éter"],
    correctAnswer: "Cadena hidrocarbonada y carboxilo",
    explanation: "La cadena es principalmente apolar y el extremo —COOH es el grupo carboxilo ácido.",
    hint: "Vuelve a la cuenta hasta cuatro y comprueba qué valencias quedan libres.",
    difficulty: 3,
    tags: ["acidos-grasos"],
  },
  {
    id: "legacy-t1-17",
    themeId: "tema-1-carbono",
    type: "choice",
    prompt: "¿Qué patrón representa el enlace éster de un triglicérido?",
    options: ["—COO—", "—NH₂", "—CHO"],
    correctAnswer: "—COO—",
    explanation: "El patrón —C(=O)—O—, abreviado —COO—, identifica un éster.",
    hint: "Vuelve a la cuenta hasta cuatro y comprueba qué valencias quedan libres.",
    difficulty: 3,
    tags: ["trigliceridos"],
  },
  {
    id: "legacy-t1-18",
    themeId: "tema-1-carbono",
    type: "choice",
    prompt: "¿Cuál de estas estructuras corresponde a una amida?",
    options: ["R—NH₂", "R—C(=O)—NH₂", "R—OH"],
    correctAnswer: "R—C(=O)—NH₂",
    explanation: "Una amida tiene el nitrógeno unido directamente a un carbonilo: —C(=O)—N—.",
    hint: "Vuelve a la cuenta hasta cuatro y comprueba qué valencias quedan libres.",
    difficulty: 3,
    tags: ["amina-o-amida"],
  },
  {
    id: "legacy-t1-19",
    themeId: "tema-1-carbono",
    type: "choice",
    prompt: "Glucosa y fructosa tienen C₆H₁₂O₆, pero una presenta aldehído y la otra cetona. Son…",
    options: ["El mismo compuesto", "Isómeros de función", "Dos aminoácidos"],
    correctAnswer: "Isómeros de función",
    explanation: "Comparten fórmula molecular, pero difieren en el grupo funcional: aldehído frente a cetona.",
    hint: "Vuelve a la cuenta hasta cuatro y comprueba qué valencias quedan libres.",
    difficulty: 3,
    tags: ["glucidos"],
  },
  {
    id: "legacy-t1-20",
    themeId: "tema-1-carbono",
    type: "choice",
    prompt: "¿Qué característica muestra que una cadena de ácido graso es insaturada?",
    options: ["Un grupo OH", "Un enlace C=C", "Un grupo NH₂"],
    correctAnswer: "Un enlace C=C",
    explanation: "La presencia de uno o más dobles enlaces C=C indica insaturación.",
    hint: "Vuelve a la cuenta hasta cuatro y comprueba qué valencias quedan libres.",
    difficulty: 3,
    tags: ["grasas-insaturadas"],
  },
  {
    id: "legacy-t1-21",
    themeId: "tema-1-carbono",
    type: "choice",
    prompt: "¿Qué enlace rompen las lipasas en los triglicéridos?",
    options: ["Enlace éster", "Enlace peptídico", "Enlace triple"],
    correctAnswer: "Enlace éster",
    explanation: "Las lipasas hidrolizan los enlaces éster que unen el glicerol con los ácidos grasos.",
    hint: "Vuelve a la cuenta hasta cuatro y comprueba qué valencias quedan libres.",
    difficulty: 3,
    tags: ["digestion-de-grasas"],
  },
  {
    id: "legacy-t1-22",
    themeId: "tema-1-carbono",
    type: "choice",
    prompt: "¿Qué dos grupos aparecen en un aminoácido típico?",
    options: ["Amino y carboxilo", "Alcohol y cetona", "Éter y aldehído"],
    correctAnswer: "Amino y carboxilo",
    explanation: "Un aminoácido típico contiene un grupo amino —NH₂ y un grupo carboxilo —COOH.",
    hint: "Vuelve a la cuenta hasta cuatro y comprueba qué valencias quedan libres.",
    difficulty: 3,
    tags: ["anatomia-de-un-aminoacido"],
  },
  {
    id: "legacy-t1-23",
    themeId: "tema-1-carbono",
    type: "choice",
    prompt: "El oxígeno tiene 6 electrones de valencia. ¿Cuántos enlaces forma habitualmente?",
    options: ["1", "2", "6"],
    correctAnswer: "2",
    explanation: "Le faltan dos electrones para completar el octeto, por lo que normalmente forma dos enlaces.",
    hint: "Vuelve a la cuenta hasta cuatro y comprueba qué valencias quedan libres.",
    difficulty: 1,
    tags: ["electrones-y-enlaces"],
  },
  {
    id: "legacy-t1-24",
    themeId: "tema-1-carbono",
    type: "choice",
    prompt: "¿Cuál es la secuencia correcta de enlaces habituales para H, O, N y C?",
    options: ["1 · 2 · 3 · 4", "4 · 3 · 2 · 1", "1 · 6 · 5 · 4"],
    correctAnswer: "1 · 2 · 3 · 4",
    explanation: "La regla práctica es H=1, O=2, N=3 y C=4 enlaces habituales.",
    hint: "Vuelve a la cuenta hasta cuatro y comprueba qué valencias quedan libres.",
    difficulty: 1,
    tags: ["chon"],
  },
  {
    id: "legacy-t1-25",
    themeId: "tema-1-carbono",
    type: "choice",
    prompt: "Para el etano C₂H₆, ¿cuál es su fórmula empírica?",
    options: ["C₂H₆", "CH₃", "CH₃—CH₃"],
    correctAnswer: "CH₃",
    explanation: "La fórmula empírica expresa la proporción mínima: dividimos los subíndices entre 2 y obtenemos CH₃.",
    hint: "Vuelve a la cuenta hasta cuatro y comprueba qué valencias quedan libres.",
    difficulty: 3,
    tags: ["formas-de-representar"],
  },
  {
    id: "legacy-t1-26",
    themeId: "tema-1-carbono",
    type: "choice",
    prompt: "¿Qué familia contiene al menos un enlace triple C≡C?",
    options: ["Alcano", "Alqueno", "Alquino"],
    correctAnswer: "Alquino",
    explanation: "Los alquinos contienen al menos un triple enlace y utilizan el sufijo -ino.",
    hint: "Vuelve a la cuenta hasta cuatro y comprueba qué valencias quedan libres.",
    difficulty: 1,
    tags: ["familias-de-hidrocarburos"],
  },
  {
    id: "legacy-t1-27",
    themeId: "tema-1-carbono",
    type: "choice",
    prompt: "¿Cuál de estas moléculas es un hidrocarburo saturado?",
    options: ["CH₃—CH₃", "CH₂=CH₂", "HC≡CH"],
    correctAnswer: "CH₃—CH₃",
    explanation: "El etano solo contiene enlaces simples, por lo que es un alcano saturado.",
    hint: "Vuelve a la cuenta hasta cuatro y comprueba qué valencias quedan libres.",
    difficulty: 1,
    tags: ["saturacion"],
  },
  {
    id: "legacy-t1-28",
    themeId: "tema-1-carbono",
    type: "choice",
    prompt: "¿Qué convierte a un anillo en heterociclo?",
    options: ["Tener únicamente carbonos", "Contener un átomo como N u O en el anillo", "Tener siempre un grupo COOH"],
    correctAnswer: "Contener un átomo como N u O en el anillo",
    explanation: "Un heterociclo contiene al menos un átomo distinto del carbono dentro del propio anillo.",
    hint: "Vuelve a la cuenta hasta cuatro y comprueba qué valencias quedan libres.",
    difficulty: 3,
    tags: ["heterociclos"],
  },
  {
    id: "legacy-t1-29",
    themeId: "tema-1-carbono",
    type: "choice",
    prompt: "Butano y 2-metilpropano tienen C₄H₁₀, pero distinta ramificación. Son isómeros de…",
    options: ["Cadena", "Posición", "Función"],
    correctAnswer: "Cadena",
    explanation: "Conservan la fórmula molecular, pero cambia el esqueleto carbonado: isomería de cadena.",
    hint: "Vuelve a la cuenta hasta cuatro y comprueba qué valencias quedan libres.",
    difficulty: 3,
    tags: ["isomeria-de-cadena"],
  },
  {
    id: "legacy-t1-30",
    themeId: "tema-1-carbono",
    type: "choice",
    prompt: "Propan-1-ol y propan-2-ol se diferencian en…",
    options: ["El número de carbonos", "La posición del OH", "La familia química"],
    correctAnswer: "La posición del OH",
    explanation: "Ambos son alcoholes C₃H₈O; cambia únicamente la posición del grupo OH.",
    hint: "Vuelve a la cuenta hasta cuatro y comprueba qué valencias quedan libres.",
    difficulty: 3,
    tags: ["isomeria-de-posicion"],
  },
  {
    id: "legacy-t1-31",
    themeId: "tema-1-carbono",
    type: "choice",
    prompt: "Etanol y dimetil éter comparten C₂H₆O, pero pertenecen a familias diferentes. Son isómeros de…",
    options: ["Cadena", "Posición", "Función"],
    correctAnswer: "Función",
    explanation: "La misma fórmula corresponde a un alcohol y un éter: isomería de función.",
    hint: "Vuelve a la cuenta hasta cuatro y comprueba qué valencias quedan libres.",
    difficulty: 3,
    tags: ["isomeria-de-funcion"],
  },
  {
    id: "legacy-t1-32",
    themeId: "tema-1-carbono",
    type: "choice",
    prompt: "¿Cuál es el primer paso antes de afirmar que dos estructuras son isómeras?",
    options: ["Comparar sus nombres", "Contar todos los átomos", "Buscar siempre un doble enlace"],
    correctAnswer: "Contar todos los átomos",
    explanation: "Los isómeros deben tener exactamente la misma cantidad de cada elemento; primero se comprueba la fórmula molecular.",
    hint: "Vuelve a la cuenta hasta cuatro y comprueba qué valencias quedan libres.",
    difficulty: 3,
    tags: ["comprobacion-de-isomeros"],
  },
  {
    id: "legacy-t1-33",
    themeId: "tema-1-carbono",
    type: "choice",
    prompt: "¿Qué información contiene 3-etil-2-metilhexano?",
    options: ["Hexano con etil en C3 y metil en C2", "Pentano con dos ramas etil", "Hexeno con un doble enlace en C3"],
    correctAnswer: "Hexano con etil en C3 y metil en C2",
    explanation: "Hexano indica una cadena principal de 6 C; 3-etil y 2-metil indican qué ramas hay y dónde se conectan.",
    hint: "Vuelve a la cuenta hasta cuatro y comprueba qué valencias quedan libres.",
    difficulty: 3,
    tags: ["desmonta-el-nombre"],
  },
  {
    id: "legacy-t1-34",
    themeId: "tema-1-carbono",
    type: "choice",
    prompt: "La fila inferior parece tener 4 C, pero existe un camino continuo superior→centro→derecha con 5 C. ¿Cuál eliges?",
    options: ["La horizontal de 4 C", "El recorrido continuo de 5 C", "Los 6 C formando una bifurcación"],
    correctAnswer: "El recorrido continuo de 5 C",
    explanation: "La cadena puede girar, pero no bifurcarse. El recorrido de 5 C es la cadena principal; el CH₃ restante será sustituyente.",
    hint: "Vuelve a la cuenta hasta cuatro y comprueba qué valencias quedan libres.",
    difficulty: 3,
    tags: ["cadena-principal"],
  },
  {
    id: "legacy-t1-35",
    themeId: "tema-1-carbono",
    type: "choice",
    prompt: "¿Cómo se llama una rama formada por —CH₂—CH₃?",
    options: ["Metil", "Etil", "Propil"],
    correctAnswer: "Etil",
    explanation: "Una rama de dos carbonos procede del etano al perder un H y se llama etil.",
    hint: "Vuelve a la cuenta hasta cuatro y comprueba qué valencias quedan libres.",
    difficulty: 3,
    tags: ["rama-o-sustituyente"],
  },
  {
    id: "legacy-t1-36",
    themeId: "tema-1-carbono",
    type: "choice",
    prompt: "Una rama puede quedar en C2 numerando desde la derecha o en C5 desde la izquierda. ¿Qué localizador se usa?",
    options: ["2", "5", "Se elige cualquiera"],
    correctAnswer: "2",
    explanation: "Se numera desde el extremo que proporcione el localizador más bajo: C2.",
    hint: "Vuelve a la cuenta hasta cuatro y comprueba qué valencias quedan libres.",
    difficulty: 3,
    tags: ["numero-mas-bajo"],
  },
  {
    id: "legacy-t1-37",
    themeId: "tema-1-carbono",
    type: "choice",
    prompt: "¿Cuál está escrito correctamente?",
    options: ["2 4 dimetil hexano", "2,4-dimetilhexano", "2-4, dimetil-hexano"],
    correctAnswer: "2,4-dimetilhexano",
    explanation: "Los números se separan con comas; números y palabras, con guiones; el nombre se escribe sin espacios.",
    hint: "Vuelve a la cuenta hasta cuatro y comprueba qué valencias quedan libres.",
    difficulty: 3,
    tags: ["puntuacion-del-nombre"],
  },
  {
    id: "legacy-t1-38",
    themeId: "tema-1-carbono",
    type: "choice",
    prompt: "¿Qué problema tiene el nombre «2-dimetilbutano» del listado?",
    options: ["Butano no existe", "Falta un localizador para la segunda rama", "El prefijo di- significa doble enlace"],
    correctAnswer: "Falta un localizador para la segunda rama",
    explanation: "Si hay dos metilos deben aparecer dos localizadores, incluso si coinciden: por ejemplo, 2,2-dimetilbutano.",
    hint: "Vuelve a la cuenta hasta cuatro y comprueba qué valencias quedan libres.",
    difficulty: 3,
    tags: ["detecta-una-errata"],
  },
  {
    id: "legacy-t1-39",
    themeId: "tema-1-carbono",
    type: "choice",
    prompt: "¿Qué fórmula corresponde a pent-2-ino?",
    options: ["CH₃—C≡C—CH₂—CH₃", "HC≡C—CH₂—CH₂—CH₃", "CH₃—CH=CH—CH₂—CH₃"],
    correctAnswer: "CH₃—C≡C—CH₂—CH₃",
    explanation: "La cadena tiene 5 C y el triple enlace está entre C2 y C3: CH₃—C≡C—CH₂—CH₃.",
    hint: "Vuelve a la cuenta hasta cuatro y comprueba qué valencias quedan libres.",
    difficulty: 3,
    tags: ["formula-un-alquino"],
  },
  {
    id: "legacy-t1-40",
    themeId: "tema-1-carbono",
    type: "choice",
    prompt: "¿Qué fórmula corresponde a hepta-2,5-dieno?",
    options: ["CH₃—CH=CH—CH₂—CH=CH—CH₃", "CH₂=CH—CH₂—CH₂—CH₂—CH=CH₂", "CH₃—C≡C—CH₂—C≡C—CH₃"],
    correctAnswer: "CH₃—CH=CH—CH₂—CH=CH—CH₃",
    explanation: "Los dobles enlaces comienzan en C2 y C5 dentro de una cadena de 7 carbonos.",
    hint: "Vuelve a la cuenta hasta cuatro y comprueba qué valencias quedan libres.",
    difficulty: 3,
    tags: ["dos-dobles-enlaces"],
  },
  {
    id: "legacy-t1-41",
    themeId: "tema-1-carbono",
    type: "choice",
    prompt: "¿Qué estructura representa nona-2,4,6-triino?",
    options: ["CH₃—C≡C—C≡C—C≡C—CH₂—CH₃", "HC≡C—CH₂—C≡C—CH₂—C≡CH", "CH₃—CH=CH—CH=CH—CH=CH—CH₂—CH₃"],
    correctAnswer: "CH₃—C≡C—C≡C—C≡C—CH₂—CH₃",
    explanation: "La cadena tiene 9 C; los triples se sitúan entre C2–C3, C4–C5 y C6–C7.",
    hint: "Vuelve a la cuenta hasta cuatro y comprueba qué valencias quedan libres.",
    difficulty: 3,
    tags: ["tres-triples-enlaces"],
  },
  {
    id: "legacy-t1-42",
    themeId: "tema-1-carbono",
    type: "choice",
    prompt: "¿Por qué 2-etilbutano no es el nombre correcto de esa conectividad?",
    options: ["Porque etil no existe", "Porque se puede trazar una cadena continua de 5 C", "Porque las ramas siempre deben ser metil"],
    correctAnswer: "Porque se puede trazar una cadena continua de 5 C",
    explanation: "La parte del supuesto etil entra en el recorrido más largo. La estructura se nombra como 3-metilpentano.",
    hint: "Vuelve a la cuenta hasta cuatro y comprueba qué valencias quedan libres.",
    difficulty: 3,
    tags: ["cadena-mas-larga"],
  },
  {
    id: "legacy-t1-43",
    themeId: "tema-1-carbono",
    type: "choice",
    prompt: "¿Cuál es el orden correcto al citar una rama etil y otra metil?",
    options: ["2-metil-3-etilhexano", "3-etil-2-metilhexano", "3-etil-2-dimetilhexano"],
    correctAnswer: "3-etil-2-metilhexano",
    explanation: "Etil se cita antes que metil por orden alfabético: 3-etil-2-metilhexano.",
    hint: "Vuelve a la cuenta hasta cuatro y comprueba qué valencias quedan libres.",
    difficulty: 3,
    tags: ["orden-alfabetico"],
  },
  {
    id: "legacy-t1-44",
    themeId: "tema-1-carbono",
    type: "choice",
    prompt: "¿Por qué CH₃=CH₃ es imposible para el alqueno neutro habitual?",
    options: ["Cada C sumaría 5 enlaces", "Cada C solo sumaría 3", "El H puede formar dos enlaces"],
    correctAnswer: "Cada C sumaría 5 enlaces",
    explanation: "Cada C tendría 3 enlaces C—H más 2 del C=C: total 5. La estructura correcta es CH₂=CH₂.",
    hint: "Vuelve a la cuenta hasta cuatro y comprueba qué valencias quedan libres.",
    difficulty: 3,
    tags: ["auditoria-de-valencias"],
  },
  {
    id: "legacy-t1-45",
    themeId: "tema-1-carbono",
    type: "choice",
    prompt: "¿Cuál de estas sustancias es un hidrocarburo?",
    options: ["C₂H₆", "C₂H₆O", "CH₃NH₂"],
    correctAnswer: "C₂H₆",
    explanation: "Un hidrocarburo contiene exclusivamente C e H; C₂H₆ es etano.",
    hint: "Vuelve a la cuenta hasta cuatro y comprueba qué valencias quedan libres.",
    difficulty: 1,
    tags: ["definicion-de-hidrocarburo"],
  },
  {
    id: "legacy-t1-46",
    themeId: "tema-1-carbono",
    type: "choice",
    prompt: "¿Qué grupo pertenece a los hidrocarburos de cadena abierta?",
    options: ["Alcanos, alquenos y alquinos", "Solo cicloalcanos", "Heterociclos con N"],
    correctAnswer: "Alcanos, alquenos y alquinos",
    explanation: "Los alcanos, alquenos y alquinos pueden formar cadenas abiertas; se distinguen por sus enlaces C—C.",
    hint: "Vuelve a la cuenta hasta cuatro y comprueba qué valencias quedan libres.",
    difficulty: 1,
    tags: ["mapa-de-clasificacion"],
  },
  {
    id: "legacy-t1-47",
    themeId: "tema-1-carbono",
    type: "choice",
    prompt: "¿Qué fórmula general corresponde a un alcano acíclico?",
    options: ["CₙH₂ₙ₊₂", "CₙH₂ₙ", "CₙH₂ₙ₋₂"],
    correctAnswer: "CₙH₂ₙ₊₂",
    explanation: "Un alcano abierto y saturado sigue CₙH₂ₙ₊₂.",
    hint: "Vuelve a la cuenta hasta cuatro y comprueba qué valencias quedan libres.",
    difficulty: 1,
    tags: ["formula-de-alcanos"],
  },
  {
    id: "legacy-t1-48",
    themeId: "tema-1-carbono",
    type: "choice",
    prompt: "¿Cuántos carbonos contiene CH₃—(CH₂)₆—CH₃?",
    options: ["6", "8", "10"],
    correctAnswer: "8",
    explanation: "Cuenta los dos CH₃ terminales y los seis CH₂: 1 + 6 + 1 = 8, octano.",
    hint: "Vuelve a la cuenta hasta cuatro y comprueba qué valencias quedan libres.",
    difficulty: 3,
    tags: ["cuenta-una-formula-condensada"],
  },
  {
    id: "legacy-t1-49",
    themeId: "tema-1-carbono",
    type: "choice",
    prompt: "Un alqueno acíclico con un solo doble enlace suele seguir…",
    options: ["CₙH₂ₙ₊₂", "CₙH₂ₙ", "CₙH₂ₙ₋₄"],
    correctAnswer: "CₙH₂ₙ",
    explanation: "Un doble enlace resta H₂ respecto al alcano: CₙH₂ₙ.",
    hint: "Vuelve a la cuenta hasta cuatro y comprueba qué valencias quedan libres.",
    difficulty: 1,
    tags: ["alqueno-sencillo"],
  },
  {
    id: "legacy-t1-50",
    themeId: "tema-1-carbono",
    type: "choice",
    prompt: "¿Qué indica el sufijo -dieno?",
    options: ["Dos dobles enlaces", "Dos triples enlaces", "Un anillo de seis C"],
    correctAnswer: "Dos dobles enlaces",
    explanation: "di- cuenta dos y -eno identifica dobles enlaces; deben aparecer dos localizadores.",
    hint: "Vuelve a la cuenta hasta cuatro y comprueba qué valencias quedan libres.",
    difficulty: 3,
    tags: ["varios-dobles-enlaces"],
  },
  {
    id: "legacy-t1-51",
    themeId: "tema-1-carbono",
    type: "choice",
    prompt: "¿Cuál muestra dos dobles enlaces conjugados?",
    options: ["C=C—C=C", "C=C—C—C=C", "C=C=C"],
    correctAnswer: "C=C—C=C",
    explanation: "En un sistema conjugado los dobles enlaces están separados por un único enlace simple.",
    hint: "Vuelve a la cuenta hasta cuatro y comprueba qué valencias quedan libres.",
    difficulty: 3,
    tags: ["dobles-conjugados"],
  },
  {
    id: "legacy-t1-52",
    themeId: "tema-1-carbono",
    type: "choice",
    prompt: "¿Qué afirmación es más correcta sobre muchos ácidos grasos poliinsaturados habituales?",
    options: ["Todos sus dobles enlaces son conjugados", "Con frecuencia están separados por un CH₂", "Siempre contienen un triple enlace"],
    correctAnswer: "Con frecuencia están separados por un CH₂",
    explanation: "En muchos PUFA naturales los dobles enlaces están separados por un grupo metileno; los conjugados son casos específicos.",
    hint: "Vuelve a la cuenta hasta cuatro y comprueba qué valencias quedan libres.",
    difficulty: 3,
    tags: ["poliinsaturadas-en-nutricion"],
  },
  {
    id: "legacy-t1-53",
    themeId: "tema-1-carbono",
    type: "choice",
    prompt: "En HC≡C—CH₃, ¿por qué el primer carbono solo lleva un H?",
    options: ["El triple ya aporta 3 enlaces", "El carbono solo admite 2 enlaces", "El H forma un triple enlace"],
    correctAnswer: "El triple ya aporta 3 enlaces",
    explanation: "El C≡C ocupa tres valencias; solo queda una para enlazarse con H.",
    hint: "Vuelve a la cuenta hasta cuatro y comprueba qué valencias quedan libres.",
    difficulty: 2,
    tags: ["hidrogeno-en-un-alquino-terminal"],
  },
  {
    id: "legacy-t1-54",
    themeId: "tema-1-carbono",
    type: "choice",
    prompt: "¿Qué fórmula molecular tiene el ciclopentano?",
    options: ["C₅H₁₂", "C₅H₁₀", "C₅H₈"],
    correctAnswer: "C₅H₁₀",
    explanation: "Un cicloalcano monocíclico saturado sigue CₙH₂ₙ: C₅H₁₀.",
    hint: "Vuelve a la cuenta hasta cuatro y comprueba qué valencias quedan libres.",
    difficulty: 1,
    tags: ["cicloalcano"],
  },
  {
    id: "legacy-t1-55",
    themeId: "tema-1-carbono",
    type: "choice",
    prompt: "C₅H₁₀ podría corresponder a…",
    options: ["Solo penteno", "Un penteno o un ciclopentano", "Solo pentano"],
    correctAnswer: "Un penteno o un ciclopentano",
    explanation: "La fórmula CₙH₂ₙ puede deberse a un doble enlace o a un anillo; necesitamos conocer la estructura.",
    hint: "Vuelve a la cuenta hasta cuatro y comprueba qué valencias quedan libres.",
    difficulty: 3,
    tags: ["una-formula-dos-posibilidades"],
  },
  {
    id: "legacy-t1-56",
    themeId: "tema-1-carbono",
    type: "choice",
    prompt: "¿Qué fórmula corresponde al benceno?",
    options: ["C₆H₆", "C₆H₁₂", "C₆H₁₄"],
    correctAnswer: "C₆H₆",
    explanation: "El benceno tiene fórmula C₆H₆ y electrones π deslocalizados.",
    hint: "Vuelve a la cuenta hasta cuatro y comprueba qué valencias quedan libres.",
    difficulty: 1,
    tags: ["benceno"],
  },
  {
    id: "legacy-t1-57",
    themeId: "tema-1-carbono",
    type: "choice",
    prompt: "En química, que un compuesto sea aromático significa principalmente que…",
    options: ["Siempre tiene olor agradable", "Posee un sistema electrónico cíclico deslocalizado", "Contiene obligatoriamente oxígeno"],
    correctAnswer: "Posee un sistema electrónico cíclico deslocalizado",
    explanation: "Aromático es una categoría estructural y electrónica; no es una descripción del olor.",
    hint: "Vuelve a la cuenta hasta cuatro y comprueba qué valencias quedan libres.",
    difficulty: 1,
    tags: ["que-significa-aromatico"],
  },
  {
    id: "legacy-t1-58",
    themeId: "tema-1-carbono",
    type: "choice",
    prompt: "¿Por qué la pirimidina no es un hidrocarburo?",
    options: ["Porque es cíclica", "Porque contiene N además de C y H", "Porque todos sus enlaces son simples"],
    correctAnswer: "Porque contiene N además de C y H",
    explanation: "Un hidrocarburo solo contiene C e H. La pirimidina es un heterociclo nitrogenado.",
    hint: "Vuelve a la cuenta hasta cuatro y comprueba qué valencias quedan libres.",
    difficulty: 3,
    tags: ["heterociclos"],
  },
  {
    id: "legacy-t1-59",
    themeId: "tema-1-carbono",
    type: "choice",
    prompt: "¿Qué característica del C=C permite la isomería cis/trans?",
    options: ["La libre rotación completa", "La rotación restringida del doble enlace", "La presencia obligatoria de N"],
    correctAnswer: "La rotación restringida del doble enlace",
    explanation: "El doble enlace restringe la rotación; grupos adecuados pueden quedar al mismo lado o en lados opuestos.",
    hint: "Vuelve a la cuenta hasta cuatro y comprueba qué valencias quedan libres.",
    difficulty: 3,
    tags: ["cis-y-trans"],
  },
];
