// Banco de preguntas ampliado.
//
// La diferencia con las preguntas originales no es solo la cantidad: cada
// distractor lleva su propia explicación. Saber por qué la respuesta correcta
// lo es sirve de poco si no sabes por qué la que elegiste no lo era, y ahí es
// donde se corrigen las ideas equivocadas.

export type BankQuestion = {
  id: string;
  themeId: string;
  type: "choice" | "multi-select" | "short";
  prompt: string;
  options?: string[];
  correctAnswer: string | string[];
  /** Por qué la correcta es correcta. */
  explanation: string;
  /** Por qué falla cada opción concreta. Clave = texto exacto de la opción. */
  optionNotes?: Record<string, string>;
  hint: string;
  difficulty: 1 | 2 | 3;
  tags: string[];
};

const b = (
  id: string,
  themeId: string,
  type: BankQuestion["type"],
  prompt: string,
  correctAnswer: BankQuestion["correctAnswer"],
  explanation: string,
  tags: string[],
  options?: string[],
  optionNotes?: Record<string, string>,
  difficulty: BankQuestion["difficulty"] = 2,
  hint = "Vuelve a la idea clave del bloque y razona qué cambia y qué permanece.",
): BankQuestion => ({
  id,
  themeId,
  type,
  prompt,
  options,
  correctAnswer,
  explanation,
  optionNotes,
  hint,
  difficulty,
  tags,
});

export const questionBank: BankQuestion[] = [
  // ───────────── TEMA 1 ─────────────
  b("b1-1", "tema-1-carbono", "choice",
    "¿Cuántos electrones de valencia tiene el nitrógeno y cuántos enlaces forma habitualmente en las moléculas neutras del curso?",
    "5 electrones de valencia y 3 enlaces",
    "Son dos números distintos: el nitrógeno tiene 5 electrones en su capa externa, pero le bastan 3 enlaces para completar el octeto.",
    ["valencia"],
    ["3 electrones de valencia y 3 enlaces", "5 electrones de valencia y 3 enlaces", "5 electrones de valencia y 5 enlaces", "4 electrones de valencia y 4 enlaces"],
    {
      "3 electrones de valencia y 3 enlaces": "Confundes ambos números al revés: los enlaces son 3, pero los electrones de valencia son 5.",
      "5 electrones de valencia y 5 enlaces": "Aquí asumes que electrones de valencia y enlaces coinciden. En el carbono coinciden por casualidad; en el nitrógeno no.",
      "4 electrones de valencia y 4 enlaces": "Eso describe al carbono, no al nitrógeno.",
    }),
  b("b1-2", "tema-1-carbono", "short",
    "Escribe la fórmula empírica de C₆H₁₂O₆.",
    "CH₂O",
    "Dividiendo los tres subíndices entre 6 queda la proporción más simple, CH₂O. Ojo: ninguna molécula real es CH₂O; la empírica es una proporción.",
    ["formulas"], undefined, undefined, 2,
    "Busca el mayor número que divida a 6, 12 y 6 a la vez."),
  b("b1-3", "tema-1-carbono", "choice",
    "¿Qué grado tiene el carbono marcado entre paréntesis en CH₃—C(CH₃)₂—CH₃?",
    "Cuaternario",
    "Ese carbono está unido a cuatro carbonos: los dos metilos de la rama y los dos extremos de la cadena. Cuatro vecinos carbono = cuaternario.",
    ["grado-carbono"],
    ["Secundario", "Terciario", "Cuaternario", "Primario"],
    {
      "Secundario": "Secundario son dos vecinos carbono. Aquí hay cuatro.",
      "Terciario": "Te falta contar un metilo: la notación (CH₃)₂ indica dos, no uno.",
      "Primario": "Primario es un solo vecino carbono, propio de los extremos de cadena.",
    }, 3),
  b("b1-4", "tema-1-carbono", "multi-select",
    "Selecciona los grupos funcionales presentes en CH₃—CO—NH—CH₃.",
    ["Amida"],
    "El conjunto C=O unido a un N es una amida completa. No hay que leerlo como una cetona y una amina por separado: el grupo funcional es el entorno entero.",
    ["grupos-funcionales"],
    ["Cetona", "Amina", "Amida", "Éster"],
    {
      "Cetona": "El C=O está unido a un nitrógeno, no a dos carbonos. Eso lo convierte en amida, no en cetona.",
      "Amina": "El nitrógeno forma parte del grupo amida; no cuenta como amina independiente.",
      "Éster": "Un éster necesita un oxígeno puente (—COO—), y aquí hay nitrógeno.",
    }, 3),
  b("b1-5", "tema-1-carbono", "choice",
    "Butan-1-ol y dietil éter comparten la fórmula C₄H₁₀O. ¿Qué tipo de isomería presentan?",
    "De función",
    "Cambia el grupo funcional: uno es alcohol y el otro un éter. Misma fórmula molecular, funciones químicas distintas.",
    ["isomeria"],
    ["De cadena", "De posición", "De función", "Cis-trans"],
    {
      "De cadena": "La isomería de cadena cambia la ramificación manteniendo la misma función.",
      "De posición": "La de posición mueve el grupo por la cadena, pero el grupo sigue siendo el mismo.",
      "Cis-trans": "Necesita un doble enlace con restricción de giro, y aquí no hay ninguno.",
    }),
  b("b1-6", "tema-1-carbono", "choice",
    "¿Cuántos hidrógenos faltan por escribir en el esqueleto CH₃—CH=CH—CH₃ si lo pasamos a fórmula molecular?",
    "C₄H₈",
    "Dos carbonos extremos con 3 H cada uno y dos centrales con 1 H cada uno: 6 + 2 = 8 hidrógenos.",
    ["formulas"],
    ["C₄H₁₀", "C₄H₈", "C₄H₆", "C₄H₄"],
    {
      "C₄H₁₀": "Ese sería el butano saturado. El doble enlace cuesta dos hidrógenos.",
      "C₄H₆": "Has restado hidrógenos de más: eso correspondería a dos insaturaciones.",
      "C₄H₄": "Demasiados hidrógenos retirados; los carbonos no sumarían cuatro enlaces.",
    }),
  b("b1-7", "tema-1-carbono", "choice",
    "¿Qué significa que el benceno sea aromático?",
    "Sus electrones π están deslocalizados por todo el anillo",
    "La deslocalización reparte los electrones por el anillo y le da una estabilidad especial. Los dobles enlaces alternos del dibujo son una convención.",
    ["aromaticos"],
    ["Que tiene olor característico", "Sus electrones π están deslocalizados por todo el anillo", "Que sus dobles enlaces saltan de posición continuamente", "Que contiene oxígeno en el anillo"],
    {
      "Que tiene olor característico": "El nombre viene históricamente del olor, pero hoy 'aromático' describe una propiedad electrónica.",
      "Que sus dobles enlaces saltan de posición continuamente": "Es la imagen que sugiere el dibujo, pero no ocurre: los electrones están repartidos de forma estable.",
      "Que contiene oxígeno en el anillo": "Eso describiría un heterociclo, no un aromático.",
    }),
  b("b1-8", "tema-1-carbono", "choice",
    "En el ácido oleico (18:1), ¿de qué grupo procede la insaturación que lo hace 'insaturado'?",
    "Del doble enlace C=C de la cadena",
    "La saturación describe la cadena hidrocarbonada. El C=O del carboxilo está en todos los ácidos grasos, también en los saturados.",
    ["saturacion", "lipidos"],
    ["Del C=O del grupo carboxilo", "Del doble enlace C=C de la cadena", "Del enlace O—H", "De los 18 carbonos"],
    {
      "Del C=O del grupo carboxilo": "Ese doble enlace lo tienen también los ácidos grasos saturados, así que no puede ser lo que los distingue.",
      "Del enlace O—H": "Es un enlace simple y no aporta insaturación.",
      "De los 18 carbonos": "La longitud de la cadena es independiente de su saturación.",
    }, 3),

  // ───────────── TEMA 1 · Grupos funcionales, hidrocarburos y aromáticos ─────────────

  // Grupos funcionales
  b("gf-1", "tema-1-carbono", "choice",
    "¿A qué familia pertenece CH₃—CH₂—OH?",
    "Alcohol",
    "El —OH está unido a un carbono alifático: es un alcohol. En concreto, etanol.",
    ["grupos-funcionales"],
    ["Éter", "Alcohol", "Fenol", "Aldehído"],
    {
      "Éter": "Un éter tendría dos carbonos unidos al oxígeno (R—O—R'), no un —OH terminal.",
      "Fenol": "Fenol requiere que el —OH esté sobre un anillo aromático. Aquí la cadena es alifática.",
      "Aldehído": "El aldehído es un C=O terminal (—CHO), no un —OH.",
    }, 1),
  b("gf-2", "tema-1-carbono", "choice",
    "¿Cuál es la diferencia estructural entre un aldehído y una cetona?",
    "En el aldehído el carbonilo va en un extremo y en la cetona entre dos carbonos",
    "Ambos comparten el carbonilo C=O. Lo que cambia es su posición dentro de la cadena, y de ahí sus diferencias de reactividad.",
    ["grupos-funcionales", "aldehido-cetona"],
    [
      "En el aldehído el carbonilo va en un extremo y en la cetona entre dos carbonos",
      "El aldehído tiene un —OH y la cetona no",
      "El aldehído tiene nitrógeno y la cetona no",
      "El aldehído es aromático y la cetona alifática",
    ],
    {
      "El aldehído tiene un —OH y la cetona no": "Ninguno de los dos lleva —OH. Los dos comparten el mismo grupo C=O.",
      "El aldehído tiene nitrógeno y la cetona no": "El nitrógeno aparecería en aminas o amidas, no en aldehídos.",
      "El aldehído es aromático y la cetona alifática": "Aromático y alifático describen la cadena, no la familia del carbonilo.",
    }),
  b("gf-3", "tema-1-carbono", "choice",
    "¿Qué familia representa R—COO—R'?",
    "Éster",
    "El grupo —COO— entre dos radicales carbonados es la firma inequívoca de un éster: se forma esterificando un ácido carboxílico con un alcohol.",
    ["grupos-funcionales", "ester-amida"],
    ["Ácido carboxílico", "Éster", "Amida", "Éter"],
    {
      "Ácido carboxílico": "El ácido lleva —OH libre, no un R' al otro lado del oxígeno: R—COOH.",
      "Amida": "La amida cambia el —O—R' por un —N: R—CO—NH—R'.",
      "Éter": "El éter no tiene carbonilo. Es solo R—O—R'.",
    }),
  b("gf-4", "tema-1-carbono", "choice",
    "¿Qué distingue exactamente a una amida de una amina?",
    "La amida lleva el nitrógeno pegado a un C=O; la amina no",
    "Las dos tienen nitrógeno, pero solo la amida forma parte de un grupo carbonilo. Sin C=O al lado, no hay amida.",
    ["grupos-funcionales", "amina-amida"],
    [
      "La amida lleva el nitrógeno pegado a un C=O; la amina no",
      "La amina tiene nitrógeno y la amida no",
      "La amida es siempre básica y la amina siempre ácida",
      "Solo se diferencian en el nombre",
    ],
    {
      "La amina tiene nitrógeno y la amida no": "Las dos llevan nitrógeno. La diferencia está en su vecino inmediato.",
      "La amida es siempre básica y la amina siempre ácida": "Es al revés en la práctica: las aminas son basicas por el par libre del N; la amida es prácticamente neutra por conjugación con el C=O.",
      "Solo se diferencian en el nombre": "Son familias químicamente distintas con reactividad muy diferente.",
    }, 3),
  b("gf-5", "tema-1-carbono", "multi-select",
    "Selecciona todos los grupos funcionales presentes en HO—CH₂—CH(NH₂)—COOH (serina, aminoácido).",
    ["Alcohol", "Amina", "Ácido carboxílico"],
    "La cadena lleva un —OH alcohólico, un —NH₂ y un —COOH. Los tres grupos coexisten en la misma molécula, cosa habitual en biomoléculas.",
    ["grupos-funcionales", "aminoacidos"],
    ["Alcohol", "Fenol", "Amina", "Ácido carboxílico", "Aldehído", "Éster"],
    {
      "Fenol": "No hay anillo aromático: el —OH está sobre un carbono alifático, es alcohol.",
      "Aldehído": "El grupo terminal es —COOH, ácido carboxílico, no un carbonilo terminal aislado.",
      "Éster": "Un éster necesita el enlace —COO—R', y no aparece aquí.",
    }, 3),
  b("gf-6", "tema-1-carbono", "choice",
    "Se hidroliza un enlace peptídico. ¿Qué grupo funcional se rompe?",
    "Una amida",
    "El enlace peptídico —CO—NH— es químicamente una amida. Romperlo devuelve los dos aminoácidos que unía.",
    ["grupos-funcionales", "amina-amida"],
    ["Un éster", "Un éter", "Una amida", "Un anhídrido"],
    {
      "Un éster": "Un éster lleva —COO—R', con oxígeno entre los dos carbonos, no nitrógeno.",
      "Un éter": "El éter no tiene carbonilo. El enlace peptídico sí.",
      "Un anhídrido": "El anhídrido enlaza dos carbonilos por un oxígeno, no es lo que une dos aminoácidos.",
    }, 3),
  b("gf-7", "tema-1-carbono", "choice",
    "¿Cuál de estas fórmulas es un fenol?",
    "C₆H₅—OH",
    "El anillo bencénico C₆H₅— unido a un —OH es la definición estructural del fenol. Su química es distinta a la de un alcohol alifático.",
    ["grupos-funcionales", "aromaticos"],
    ["CH₃—CH₂—OH", "C₆H₅—OH", "CH₃—O—CH₃", "CH₃—CHO"],
    {
      "CH₃—CH₂—OH": "Es etanol, un alcohol. El —OH está sobre un carbono alifático.",
      "CH₃—O—CH₃": "Es un éter (dimetiléter), sin —OH.",
      "CH₃—CHO": "Es acetaldehído, con el carbonilo terminal característico.",
    }),
  b("gf-8", "tema-1-carbono", "short",
    "Nombra el grupo funcional presente en CH₃—CH₂—CO—CH₃.",
    "Cetona",
    "El C=O está entre dos carbonos, así que es una cetona. En concreto, butan-2-ona.",
    ["grupos-funcionales", "aldehido-cetona"], undefined, undefined, 1,
    "Mira si el C=O tiene un H al lado o dos carbonos."),

  // Alcanos y familia de hidrocarburos
  b("hc-1", "tema-1-carbono", "choice",
    "¿Cuántos hidrógenos tiene el heptano?",
    "16",
    "Para un alcano acíclico de n carbonos, CₙH₂ₙ₊₂. Con n=7: 2·7+2 = 16 hidrógenos.",
    ["hidrocarburos", "alcanos"],
    ["14", "16", "18", "12"],
    {
      "14": "Ese sería el número para una cadena cíclica (CₙH₂ₙ) o para un alqueno con un doble enlace.",
      "18": "Estás sumando dos hidrógenos de más; con n=8 sí saldría 18.",
      "12": "Estás restando dos insaturaciones que no existen: el heptano es saturado.",
    }),
  b("hc-2", "tema-1-carbono", "choice",
    "El compuesto CH₃—CH₂—CH=CH—CH₃ es…",
    "Un alqueno con un doble enlace en el carbono 2",
    "Cinco carbonos, un doble enlace que empieza en C2: es el pent-2-eno. La terminación -eno confirma la familia.",
    ["hidrocarburos", "alquenos"],
    [
      "Un alcano lineal",
      "Un alqueno con un doble enlace en el carbono 2",
      "Un alquino con un triple enlace",
      "Un compuesto aromático",
    ],
    {
      "Un alcano lineal": "Un alcano solo tiene enlaces simples; aquí hay un C=C.",
      "Un alquino con un triple enlace": "El signo = es doble enlace, no triple.",
      "Un compuesto aromático": "No hay anillo. Aromático exige la deslocalización del anillo bencénico.",
    }),
  b("hc-3", "tema-1-carbono", "short",
    "¿Cuántos hidrógenos tiene el hex-2-ino?",
    "10",
    "Alquino con un triple enlace: CₙH₂ₙ₋₂. Con n=6: 2·6−2 = 10 hidrógenos.",
    ["hidrocarburos", "alquinos"], undefined, undefined, 2,
    "Cada insaturación cuesta dos hidrógenos; el triple enlace cuesta cuatro respecto al alcano."),
  b("hc-4", "tema-1-carbono", "choice",
    "¿Cuál es el nombre correcto de CH₃—CH(CH₃)—CH₂—CH₃?",
    "2-metilbutano",
    "La cadena principal más larga tiene 4 carbonos (butano). El sustituyente —CH₃ queda en el C2 al numerar desde el extremo más cercano.",
    ["hidrocarburos", "nomenclatura"],
    ["2-metilbutano", "3-metilbutano", "2-metilpropano", "2-etilpropano"],
    {
      "3-metilbutano": "Sería el mismo compuesto numerado por el extremo equivocado: el localizador 2 es menor que 3.",
      "2-metilpropano": "El isobutano solo tiene 4 carbonos totales; aquí hay 5.",
      "2-etilpropano": "Un etilo en propano no puede existir así: al añadirlo, la cadena principal pasa a ser de 4 carbonos.",
    }, 3),
  b("hc-5", "tema-1-carbono", "choice",
    "¿Qué grado tiene el carbono central en CH₃—CH(CH₃)—CH₂—CH₃?",
    "Terciario",
    "Ese carbono está unido a tres carbonos: dos CH₃ y un CH₂. Con tres vecinos carbono, es terciario.",
    ["hidrocarburos", "grado-carbono"],
    ["Primario", "Secundario", "Terciario", "Cuaternario"],
    {
      "Primario": "Un carbono primario tiene un solo vecino carbono; los extremos de la cadena lo son.",
      "Secundario": "Secundario son dos vecinos carbono; aquí hay tres.",
      "Cuaternario": "Cuaternario son cuatro vecinos carbono y ningún hidrógeno; este todavía lleva un H.",
    }),
  b("hc-6", "tema-1-carbono", "choice",
    "El ciclopentano tiene fórmula molecular…",
    "C₅H₁₀",
    "Un cicloalcano saturado sigue CₙH₂ₙ: cerrar el anillo cuesta dos hidrógenos respecto al alcano abierto.",
    ["hidrocarburos", "cicloalcanos"],
    ["C₅H₁₀", "C₅H₁₂", "C₅H₈", "C₅H₆"],
    {
      "C₅H₁₂": "Esa es la fórmula del pentano abierto; al cerrar el anillo se pierden dos H.",
      "C₅H₈": "Esa fórmula tiene dos grados de insaturación: un ciclopenteno o un pent-2-ino.",
      "C₅H₆": "Esa fórmula tendría tres insaturaciones; sería un anillo con dos dobles enlaces.",
    }, 3),
  b("hc-7", "tema-1-carbono", "multi-select",
    "Selecciona los compuestos saturados.",
    ["Butano", "Ciclohexano"],
    "Saturado significa sin C=C ni C≡C. El butano y el ciclohexano solo tienen enlaces simples; el propeno y el etino no.",
    ["hidrocarburos", "saturacion"],
    ["Butano", "Propeno", "Ciclohexano", "Etino"],
    {
      "Propeno": "El sufijo -eno indica un doble enlace; hay insaturación.",
      "Etino": "El sufijo -ino indica triple enlace; también insaturado.",
    }),
  b("hc-8", "tema-1-carbono", "choice",
    "¿Por qué CH₃=CH₃ no puede existir como compuesto neutro?",
    "Cada carbono sumaría cinco enlaces",
    "Cada carbono llevaría tres hidrógenos (3 enlaces) más el doble (2 enlaces): 3+2=5. El carbono neutro nunca suma más de cuatro.",
    ["hidrocarburos", "auditoria-formula"],
    [
      "Cada carbono sumaría cinco enlaces",
      "El doble enlace vale uno, no dos",
      "No existe ningún hidrocarburo con doble enlace",
      "Le faltan hidrógenos",
    ],
    {
      "El doble enlace vale uno, no dos": "El doble enlace ocupa dos valencias; ese es precisamente el motivo de que 3+2=5 no valga.",
      "No existe ningún hidrocarburo con doble enlace": "Los alquenos existen sin problema; el error está en la escritura concreta.",
      "Le faltan hidrógenos": "Le sobran: la fórmula correcta con doble enlace es CH₂=CH₂ (eteno), con dos H por carbono.",
    }, 3),

  // Aromáticos y benceno
  b("ar-1", "tema-1-carbono", "choice",
    "¿Qué significa que el benceno sea «aromático»?",
    "Sus electrones π están deslocalizados por el anillo, dándole estabilidad",
    "El término «aromático» no describe olor: describe una estructura electrónica particular con seis electrones π deslocalizados sobre los seis carbonos.",
    ["aromaticos", "benceno"],
    [
      "Que tiene olor característico",
      "Sus electrones π están deslocalizados por el anillo, dándole estabilidad",
      "Que se descompone al calentar",
      "Que tiene dobles enlaces que saltan continuamente",
    ],
    {
      "Que tiene olor característico": "El nombre viene históricamente del olor, pero hoy describe una propiedad electrónica.",
      "Que se descompone al calentar": "Justo lo contrario: el benceno es especialmente estable.",
      "Que tiene dobles enlaces que saltan continuamente": "Es una imagen intuitiva pero incorrecta. Los electrones están repartidos de forma estable, no oscilan.",
    }),
  b("ar-2", "tema-1-carbono", "choice",
    "¿Cuál es la fórmula molecular del benceno?",
    "C₆H₆",
    "El anillo bencénico tiene seis carbonos y seis hidrógenos, uno por cada carbono del anillo.",
    ["aromaticos", "benceno"],
    ["C₆H₆", "C₆H₁₂", "C₆H₁₄", "C₆H₈"],
    {
      "C₆H₁₂": "Esa es la fórmula del ciclohexano, un ciclo saturado sin aromaticidad.",
      "C₆H₁₄": "Sería el hexano acíclico: cadena abierta sin doble enlace ni ciclo.",
      "C₆H₈": "No corresponde a ninguna estructura estable habitual del carbono con esa arquitectura.",
    }, 1),
  b("ar-3", "tema-1-carbono", "choice",
    "¿Cuál de estos compuestos NO es aromático?",
    "Ciclohexano",
    "El ciclohexano es un anillo saturado sin electrones π deslocalizados. Los otros tres son aromáticos: benceno, tolueno (metilbenceno) y fenol (hidroxibenceno).",
    ["aromaticos"],
    ["Benceno", "Ciclohexano", "Tolueno", "Fenol"],
    {
      "Benceno": "Es el aromático arquetípico.",
      "Tolueno": "Es benceno con un metilo; sigue siendo aromático.",
      "Fenol": "Es benceno con un —OH; sigue siendo aromático.",
    }),
  b("ar-4", "tema-1-carbono", "choice",
    "El fenol se comporta químicamente distinto a un alcohol alifático como el etanol. ¿Por qué?",
    "Porque el anillo aromático estabiliza al ion fenóxido y hace el —OH más ácido",
    "Cuando el fenol pierde el H del —OH, la carga negativa se deslocaliza por el anillo aromático y el ion resultante es estable. Ese efecto electrónico hace al fenol muchísimo más ácido que un alcohol alifático.",
    ["aromaticos", "benceno", "fenol"],
    [
      "Porque el fenol tiene más átomos de oxígeno",
      "Porque el anillo aromático estabiliza al ion fenóxido y hace el —OH más ácido",
      "Porque el fenol es líquido y el etanol gas",
      "Porque el fenol tiene dobles enlaces y el etanol no",
    ],
    {
      "Porque el fenol tiene más átomos de oxígeno": "Los dos tienen un único oxígeno.",
      "Porque el fenol es líquido y el etanol gas": "Ambos son líquidos a temperatura ambiente. La reactividad no depende del estado físico.",
      "Porque el fenol tiene dobles enlaces y el etanol no": "El etanol no tiene C=C, pero la clave no son «dobles enlaces» sin más: es la deslocalización del anillo aromático completo.",
    }, 3),
  b("ar-5", "tema-1-carbono", "multi-select",
    "Selecciona todos los compuestos que contienen anillo aromático.",
    ["Fenilalanina", "Estradiol"],
    "La fenilalanina lleva un anillo bencénico en su cadena lateral. El estradiol es un esteroide con un anillo aromático (el A). La glucosa y el ciclohexano son cíclicos pero no aromáticos.",
    ["aromaticos", "biomoleculas"],
    ["Fenilalanina", "Glucosa", "Estradiol", "Ciclohexano"],
    {
      "Glucosa": "La glucosa en forma cíclica forma un anillo de piranosa saturado, sin aromaticidad.",
      "Ciclohexano": "Es un anillo saturado de seis carbonos, sin electrones π deslocalizados.",
    }, 3),
  b("ar-6", "tema-1-carbono", "choice",
    "¿Por qué es incorrecto dibujar el benceno como tres dobles enlaces alternos fijos?",
    "Porque todos los enlaces del anillo son equivalentes y de longitud intermedia",
    "Si hubiera tres dobles alternos fijos, la mitad de los enlaces serían más cortos que los simples. Midiéndolo se comprueba que no: son todos iguales.",
    ["aromaticos", "benceno"],
    [
      "Porque el benceno no existe",
      "Porque todos los enlaces del anillo son equivalentes y de longitud intermedia",
      "Porque el dibujo no importa mientras la fórmula sea correcta",
      "Porque tiene enlaces triples",
    ],
    {
      "Porque el benceno no existe": "Existe y es uno de los compuestos aromáticos más comunes.",
      "Porque el dibujo no importa mientras la fórmula sea correcta": "El dibujo importa porque transmite un modelo de la estructura. Uno con dobles fijos comunica algo falso.",
      "Porque tiene enlaces triples": "No hay ningún triple enlace en el benceno. La deslocalización es de electrones π sobre enlaces intermedios entre simple y doble.",
    }, 3),

  // ───────────── TEMA 2 ─────────────
  b("b2-1", "tema-2-hidratos", "choice",
    "Clasifica la ribosa según carbonos y grupo carbonilo.",
    "Aldopentosa",
    "Cinco carbonos la hacen pentosa, y su carbonilo terminal de aldehído la hace aldosa.",
    ["monosacaridos"],
    ["Cetopentosa", "Aldopentosa", "Aldohexosa", "Cetohexosa"],
    {
      "Cetopentosa": "El número de carbonos es correcto, pero su carbonilo es un aldehído, no una cetona.",
      "Aldohexosa": "Seis carbonos correspondería a glucosa o galactosa; la ribosa tiene cinco.",
      "Cetohexosa": "Eso describe a la fructosa.",
    }),
  b("b2-2", "tema-2-hidratos", "choice",
    "¿Qué enzima hidroliza la sacarosa y qué monosacáridos libera?",
    "Sacarasa; glucosa y fructosa",
    "El nombre de la enzima sigue al sustrato, y la sacarosa está formada por glucosa unida a fructosa.",
    ["disacaridos"],
    ["Lactasa; glucosa y galactosa", "Sacarasa; glucosa y fructosa", "Maltasa; dos glucosas", "Amilasa; glucosa y galactosa"],
    {
      "Lactasa; glucosa y galactosa": "Eso corresponde a la lactosa, no a la sacarosa.",
      "Maltasa; dos glucosas": "Eso corresponde a la maltosa.",
      "Amilasa; glucosa y galactosa": "La amilasa actúa sobre el almidón, y no libera galactosa en ningún caso.",
    }),
  b("b2-3", "tema-2-hidratos", "choice",
    "El glucógeno está más ramificado que el almidón. ¿Qué ventaja funcional aporta eso?",
    "Más extremos libres, y por tanto más puntos desde los que movilizar glucosa deprisa",
    "Las enzimas trabajan por los extremos de la cadena. Más ramas significa más frentes de ataque simultáneos.",
    ["polisacaridos"],
    ["Hace el enlace más resistente a la hidrólisis", "Más extremos libres, y por tanto más puntos desde los que movilizar glucosa deprisa", "Permite almacenar glucosa sin gastar energía", "Convierte los enlaces α en β"],
    {
      "Hace el enlace más resistente a la hidrólisis": "Al contrario: la ramificación facilita el acceso enzimático, no lo dificulta.",
      "Permite almacenar glucosa sin gastar energía": "Sintetizar glucógeno consume energía, esté ramificado o no.",
      "Convierte los enlaces α en β": "La ramificación es α(1→6); el tipo de enlace no cambia de α a β.",
    }, 3),
  b("b2-4", "tema-2-hidratos", "choice",
    "¿En qué se diferencian α-D-glucosa y β-D-glucosa?",
    "En la orientación del —OH del carbono anomérico",
    "Ambas son D-glucosa: la configuración general es la misma. Solo cambia hacia dónde apunta el grupo del C1 tras ciclarse.",
    ["anomeria"],
    ["En el número de carbonos", "En la orientación del —OH del carbono anomérico", "En que una es aldosa y otra cetosa", "En su configuración D o L"],
    {
      "En el número de carbonos": "Las dos son hexosas con la misma fórmula.",
      "En que una es aldosa y otra cetosa": "Las dos proceden de una aldosa; eso no cambia al ciclarse.",
      "En su configuración D o L": "Aquí está la confusión típica: D/L es configuración y no cambia; α/β es anomería.",
    }),
  b("b2-5", "tema-2-hidratos", "multi-select",
    "¿Qué efectos son propios sobre todo de la fibra soluble?",
    ["Forma geles viscosos", "Es fermentada por la microbiota"],
    "La solubilidad permite formar geles y ser sustrato de fermentación en el colon.",
    ["fibra"],
    ["Forma geles viscosos", "Es fermentada por la microbiota", "Aporta sobre todo volumen fecal", "No se digiere en el intestino delgado"],
    {
      "Aporta sobre todo volumen fecal": "Ese es el efecto predominante de la fracción insoluble.",
      "No se digiere en el intestino delgado": "Cierto, pero lo comparten las dos fracciones: no distingue soluble de insoluble.",
    }, 3),
  b("b2-6", "tema-2-hidratos", "choice",
    "¿Por qué la celulosa aporta fibra y el almidón aporta glucosa, si ambos son polímeros de glucosa?",
    "Porque las enzimas humanas no hidrolizan el enlace β(1→4)",
    "Los monómeros son idénticos; lo que cambia es la orientación del enlace, y la amilasa solo reconoce α(1→4).",
    ["polisacaridos"],
    ["Porque la celulosa no contiene glucosa realmente", "Porque las enzimas humanas no hidrolizan el enlace β(1→4)", "Porque la celulosa tiene menos carbonos", "Porque el almidón se absorbe intacto"],
    {
      "Porque la celulosa no contiene glucosa realmente": "Sí la contiene: es un polímero de glucosa puro.",
      "Porque la celulosa tiene menos carbonos": "Sus unidades son la misma hexosa, con los mismos seis carbonos.",
      "Porque el almidón se absorbe intacto": "No se absorbe ningún polisacárido intacto: la digestión termina en monosacáridos.",
    }),
  b("b2-7", "tema-2-hidratos", "short",
    "¿Qué monosacárido comparten la lactosa y la maltosa?",
    "Glucosa",
    "Lactosa es galactosa + glucosa y maltosa es glucosa + glucosa: la glucosa está en las dos.",
    ["disacaridos"], undefined, undefined, 1,
    "Escribe la composición de cada disacárido y busca la pieza común."),
  b("b2-8", "tema-2-hidratos", "choice",
    "Una persona con déficit de lactasa tolera bien el queso curado. ¿Por qué?",
    "Porque durante la curación buena parte de la lactosa desaparece",
    "El problema es el disacárido concreto, no los lácteos en bloque ni sus proteínas. Un queso curado contiene muy poca lactosa.",
    ["lactosa", "dietetica"],
    ["Porque el queso no contiene proteínas lácteas", "Porque durante la curación buena parte de la lactosa desaparece", "Porque la grasa del queso bloquea la lactosa", "Porque el queso aporta su propia lactasa"],
    {
      "Porque el queso no contiene proteínas lácteas": "Sí las contiene; además, la intolerancia a la lactosa no es un problema con las proteínas.",
      "Porque la grasa del queso bloquea la lactosa": "La grasa no impide que la lactosa llegue al intestino.",
      "Porque el queso aporta su propia lactasa": "Los quesos no aportan lactasa humana funcional.",
    }, 3),

  // ───────────── TEMA 3 ─────────────
  b("b3-1", "tema-3-lipidos", "choice",
    "¿Qué le ocurre a una cadena de ácido graso cuando aparece un doble enlace cis?",
    "Se dobla, y eso dificulta que las cadenas se apilen entre sí",
    "El codo del cis impide el empaquetamiento compacto, y por eso las grasas insaturadas suelen ser líquidas a temperatura ambiente.",
    ["acidos-grasos"],
    ["Se alarga", "Se dobla, y eso dificulta que las cadenas se apilen entre sí", "Se vuelve más rígida y recta", "Pierde el grupo carboxilo"],
    {
      "Se alarga": "El número de carbonos no cambia al introducir una insaturación.",
      "Se vuelve más rígida y recta": "La configuración trans sí mantiene la cadena bastante recta; la cis la dobla.",
      "Pierde el grupo carboxilo": "El carboxilo permanece: sigue siendo un ácido graso.",
    }),
  b("b3-2", "tema-3-lipidos", "choice",
    "¿Qué indica el 'n-3' del ácido α-linolénico, 18:3 n-3?",
    "Que el primer doble enlace está a tres carbonos del extremo metilo",
    "La notación omega localiza únicamente el primer doble enlace, y se cuenta desde el extremo opuesto al carboxilo.",
    ["omega"],
    ["Que tiene tres dobles enlaces", "Que el primer doble enlace está a tres carbonos del extremo metilo", "Que tiene tres carbonos", "Que el primer doble enlace está a tres carbonos del carboxilo"],
    {
      "Que tiene tres dobles enlaces": "Eso lo dice el 3 que va después de los dos puntos, no el 'n-3'. Coinciden por casualidad en este ácido graso.",
      "Que tiene tres carbonos": "Los carbonos son 18, el número anterior a los dos puntos.",
      "Que el primer doble enlace está a tres carbonos del carboxilo": "Se cuenta desde el extremo metilo, que es el contrario al carboxilo.",
    }, 3),
  b("b3-3", "tema-3-lipidos", "choice",
    "¿Qué distingue estructuralmente a un fosfolípido de un triglicérido?",
    "Sustituye un ácido graso por un fosfato con cabeza polar",
    "Ese cambio en la tercera posición del glicerol lo vuelve anfipático, y por eso forma bicapas en lugar de gotas.",
    ["fosfolipidos"],
    ["Tiene cuatro ácidos grasos en vez de tres", "Sustituye un ácido graso por un fosfato con cabeza polar", "No contiene glicerol", "Sus ácidos grasos son siempre saturados"],
    {
      "Tiene cuatro ácidos grasos en vez de tres": "El glicerol solo tiene tres posiciones disponibles.",
      "No contiene glicerol": "Los glicerofosfolípidos sí lo contienen; los que usan esfingosina son otra familia.",
      "Sus ácidos grasos son siempre saturados": "Pueden ser saturados o insaturados, igual que en un triglicérido.",
    }),
  b("b3-4", "tema-3-lipidos", "multi-select",
    "¿Qué funciones cumple el colesterol en el organismo?",
    ["Modula la fluidez de la membrana", "Es precursor de ácidos biliares", "Es precursor de hormonas esteroideas"],
    "El colesterol no es un contaminante: el cuerpo lo fabrica y lo usa como material estructural y como punto de partida de varias moléculas.",
    ["colesterol"],
    ["Modula la fluidez de la membrana", "Es precursor de ácidos biliares", "Es precursor de hormonas esteroideas", "Transporta oxígeno en la sangre"],
    {
      "Transporta oxígeno en la sangre": "Eso lo hace la hemoglobina, una proteína con hierro.",
    }),
  b("b3-5", "tema-3-lipidos", "choice",
    "¿Qué hace exactamente la lipoproteína lipasa (LPL) sobre un quilomicrón?",
    "Hidroliza sus triglicéridos y libera ácidos grasos a los tejidos",
    "La LPL vacía la carga de la partícula. No la destruye ni separa su parte proteica de la lipídica.",
    ["lipoproteinas"],
    ["Separa la proteína de la grasa", "Hidroliza sus triglicéridos y libera ácidos grasos a los tejidos", "Convierte el quilomicrón en HDL directamente", "Sintetiza colesterol dentro de la partícula"],
    {
      "Separa la proteína de la grasa": "Es un error frecuente: la LPL es una lipasa, y actúa sobre enlaces éster de triglicéridos.",
      "Convierte el quilomicrón en HDL directamente": "Los quilomicrones dejan remanentes; las HDL tienen otro origen y otra función.",
      "Sintetiza colesterol dentro de la partícula": "La LPL hidroliza, no sintetiza.",
    }, 3),
  b("b3-6", "tema-3-lipidos", "short",
    "¿Qué tipo de enlace une el glicerol con cada ácido graso en un triglicérido?",
    "Éster",
    "Un alcohol (—OH del glicerol) más un ácido (—COOH del ácido graso) da un éster, liberando agua.",
    ["trigliceridos"], undefined, undefined, 1,
    "Piensa en la reacción entre un alcohol y un ácido carboxílico."),
  b("b3-7", "tema-3-lipidos", "choice",
    "Alguien reduce la grasa saturada de su dieta. ¿Qué dato falta para valorar el efecto?",
    "Por qué nutriente o alimento la sustituye",
    "El efecto de reducir un nutriente depende de qué ocupa su lugar: no es igual sustituirla por aceite de oliva que por azúcar.",
    ["dietetica"],
    ["Cuántas calorías tenía antes", "Por qué nutriente o alimento la sustituye", "Su peso corporal exacto", "La marca del producto"],
    {
      "Cuántas calorías tenía antes": "Ayuda al contexto, pero no dice qué ha entrado en lugar de la grasa retirada.",
      "Su peso corporal exacto": "No determina el efecto de una sustitución de nutrientes.",
      "La marca del producto": "Lo relevante es la composición y el patrón, no la marca.",
    }),
  b("b3-8", "tema-3-lipidos", "choice",
    "¿Por qué un aceite muy poliinsaturado se enrancia antes?",
    "Porque sus dobles enlaces son los puntos vulnerables a la oxidación",
    "Cada doble enlace es un punto donde el oxígeno puede atacar; más insaturaciones, más vulnerabilidad.",
    ["oxidacion"],
    ["Porque contiene más agua", "Porque sus dobles enlaces son los puntos vulnerables a la oxidación", "Porque tiene cadenas más cortas", "Porque contiene más colesterol"],
    {
      "Porque contiene más agua": "Los aceites contienen muy poca agua, y no es lo que explica el enranciamiento oxidativo.",
      "Porque tiene cadenas más cortas": "La longitud influye en el punto de fusión, no en la susceptibilidad a oxidarse.",
      "Porque contiene más colesterol": "Los aceites vegetales prácticamente no contienen colesterol.",
    }),

  // ───────────── TEMA 4 ─────────────
  b("b4-1", "tema-4-proteinas", "choice",
    "¿Qué determina las propiedades químicas de un aminoácido concreto?",
    "Su cadena lateral R",
    "El grupo amino, el carboxilo, el H y el carbono α son comunes a todos. La única parte variable es R.",
    ["aminoacidos"],
    ["Su grupo amino", "Su grupo carboxilo", "Su cadena lateral R", "Su carbono α"],
    {
      "Su grupo amino": "Lo tienen los veinte por igual, así que no puede diferenciarlos.",
      "Su grupo carboxilo": "También es común a todos.",
      "Su carbono α": "Es el esqueleto compartido; no aporta diferencias entre aminoácidos.",
    }, 1),
  b("b4-2", "tema-4-proteinas", "choice",
    "Al cocer un huevo, ¿qué le ocurre exactamente a sus proteínas?",
    "Se desnaturalizan: pierden el plegamiento sin romperse la cadena",
    "El calor destruye las interacciones que sostenían la forma tridimensional, pero los enlaces peptídicos siguen intactos.",
    ["desnaturalizacion"],
    ["Se hidrolizan en aminoácidos libres", "Se desnaturalizan: pierden el plegamiento sin romperse la cadena", "Se convierten en glúcidos", "Pierden su estructura primaria"],
    {
      "Se hidrolizan en aminoácidos libres": "Eso requiere hidrólisis enzimática o química; cocinar no rompe los enlaces peptídicos de forma masiva.",
      "Se convierten en glúcidos": "No hay ninguna transformación de proteína en carbohidrato al cocinar.",
      "Pierden su estructura primaria": "La primaria es la secuencia y se conserva: es justo lo que la desnaturalización no toca.",
    }),
  b("b4-3", "tema-4-proteinas", "choice",
    "¿Qué NO hace una enzima?",
    "Volver favorable una reacción que no lo era",
    "Una enzima acelera el camino hacia el equilibrio, pero no cambia dónde está ese equilibrio ni aporta energía.",
    ["enzimas"],
    ["Reducir la energía de activación", "Volver favorable una reacción que no lo era", "Reconocer su sustrato en el centro activo", "Acelerar la llegada al equilibrio"],
    {
      "Reducir la energía de activación": "Eso sí lo hace: es precisamente su mecanismo.",
      "Reconocer su sustrato en el centro activo": "Eso sí lo hace, y explica su especificidad.",
      "Acelerar la llegada al equilibrio": "Eso sí lo hace, en ambos sentidos de la reacción.",
    }, 3),
  b("b4-4", "tema-4-proteinas", "short",
    "¿Cuántos aminoácidos se consideran esenciales en el adulto según el criterio actual?",
    "9",
    "Nueve, incluida la histidina. Los textos que dicen ocho dejan la histidina fuera con un criterio antiguo.",
    ["aminoacidos"], undefined, undefined, 2,
    "Cuidado con los libros antiguos: uno de ellos se incorporó más tarde."),
  b("b4-5", "tema-4-proteinas", "choice",
    "¿Por qué el ácido gástrico facilita la digestión de las proteínas si no rompe enlaces peptídicos?",
    "Porque las despliega y deja los enlaces accesibles a las proteasas",
    "Desnaturalizar expone la cadena. Las proteasas hacen el corte después, sobre una estructura ya abierta.",
    ["digestion", "desnaturalizacion"],
    ["Porque las convierte directamente en aminoácidos", "Porque las despliega y deja los enlaces accesibles a las proteasas", "Porque activa la lactasa", "Porque emulsiona las proteínas"],
    {
      "Porque las convierte directamente en aminoácidos": "Eso sería hidrólisis completa, y el ácido por sí solo no la realiza.",
      "Porque activa la lactasa": "La lactasa actúa sobre un disacárido, no sobre proteínas.",
      "Porque emulsiona las proteínas": "Emulsionar es un proceso propio de las grasas, y lo hacen las sales biliares.",
    }, 3),
  b("b4-6", "tema-4-proteinas", "multi-select",
    "¿Qué interacciones contribuyen al plegamiento de una proteína?",
    ["Puentes de hidrógeno", "Interacciones hidrófobas", "Puentes disulfuro", "Interacciones iónicas"],
    "El plegamiento no lo sostiene una sola fuerza: es la suma de varias interacciones entre cadenas laterales y esqueleto.",
    ["estructura-proteica"],
    ["Puentes de hidrógeno", "Interacciones hidrófobas", "Puentes disulfuro", "Interacciones iónicas", "Enlaces glucosídicos"],
    {
      "Enlaces glucosídicos": "Ese enlace une azúcares entre sí; no interviene en el plegamiento proteico.",
    }),
  b("b4-7", "tema-4-proteinas", "choice",
    "Un inhibidor competitivo ocupa el centro activo. ¿Qué efecto tiene aumentar mucho el sustrato?",
    "Reduce el efecto relativo del inhibidor, porque compiten por el mismo sitio",
    "Al haber más moléculas de sustrato, la probabilidad de que ocupen el centro activo antes que el inhibidor aumenta.",
    ["enzimas"],
    ["No cambia nada", "Reduce el efecto relativo del inhibidor, porque compiten por el mismo sitio", "Destruye el inhibidor", "Desnaturaliza la enzima"],
    {
      "No cambia nada": "Sí cambia: la competencia por un mismo sitio depende de las concentraciones relativas.",
      "Destruye el inhibidor": "El sustrato no degrada al inhibidor; simplemente compite con él.",
      "Desnaturaliza la enzima": "Aumentar sustrato no altera el plegamiento de la enzima.",
    }, 3),
  b("b4-8", "tema-4-proteinas", "choice",
    "¿Qué afirmación sobre la complementariedad proteica vegetal es correcta hoy?",
    "Basta con combinar fuentes variadas a lo largo de la dieta",
    "El organismo mantiene una reserva de aminoácidos que permite integrar aportes a lo largo del día; no hace falta que coincidan en el mismo plato.",
    ["proteina-dieta"],
    ["Legumbre y cereal deben tomarse en la misma comida", "Basta con combinar fuentes variadas a lo largo de la dieta", "Las proteínas vegetales no pueden cubrir el patrón esencial", "Solo la soja aporta aminoácidos indispensables"],
    {
      "Legumbre y cereal deben tomarse en la misma comida": "Es la versión antigua de la recomendación; ya no se sostiene.",
      "Las proteínas vegetales no pueden cubrir el patrón esencial": "Sí pueden, combinando fuentes y con energía suficiente.",
      "Solo la soja aporta aminoácidos indispensables": "La soja tiene buen perfil, pero no es la única fuente vegetal válida.",
    }),

  // ───────────── TEMA 5 ─────────────
  b("b5-1", "tema-5-acidos-nucleicos", "choice",
    "¿Qué diferencia química hay entre la ribosa y la desoxirribosa?",
    "La desoxirribosa tiene un oxígeno menos",
    "El prefijo 'desoxi-' lo dice literalmente. Esa ausencia hace al ADN algo más estable, lo que conviene a una molécula que debe durar.",
    ["adn-arn"],
    ["La desoxirribosa tiene un carbono menos", "La desoxirribosa tiene un oxígeno menos", "La desoxirribosa tiene un fosfato más", "Son la misma molécula con distinto nombre"],
    {
      "La desoxirribosa tiene un carbono menos": "Las dos son pentosas: cinco carbonos cada una.",
      "La desoxirribosa tiene un fosfato más": "El fosfato no forma parte del azúcar, se añade aparte en el nucleótido.",
      "Son la misma molécula con distinto nombre": "Son distintas, y esa diferencia separa al ADN del ARN.",
    }),
  b("b5-2", "tema-5-acidos-nucleicos", "short",
    "Escribe la hebra complementaria de ADN de 5′-TTAGC-3′, indicando su orientación.",
    "3′-AATCG-5′",
    "T con A, T con A, A con T, G con C y C con G, recorrida en sentido antiparalelo.",
    ["adn-arn"], undefined, undefined, 3,
    "Empareja base a base y recuerda que las hebras van en sentidos opuestos."),
  b("b5-3", "tema-5-acidos-nucleicos", "choice",
    "¿Dónde está el codón y dónde el anticodón?",
    "El codón en el ARNm y el anticodón en el ARNt",
    "El mensajero lleva la secuencia a leer; el de transferencia trae el aminoácido y reconoce el codón por complementariedad.",
    ["traduccion"],
    ["Los dos en el ARNm", "El codón en el ARNt y el anticodón en el ARNm", "El codón en el ARNm y el anticodón en el ARNt", "Los dos en el ADN"],
    {
      "Los dos en el ARNm": "El anticodón pertenece a otra molécula: el ARN de transferencia.",
      "El codón en el ARNt y el anticodón en el ARNm": "Están intercambiados.",
      "Los dos en el ADN": "El código se lee sobre el ARN mensajero, no directamente sobre el ADN.",
    }),
  b("b5-4", "tema-5-acidos-nucleicos", "choice",
    "¿Qué significa que el código genético sea degenerado?",
    "Varios codones distintos pueden codificar el mismo aminoácido",
    "Hay 64 combinaciones para 20 aminoácidos, así que sobran codones. Eso da cierta tolerancia frente a mutaciones.",
    ["dogma-central"],
    ["Que pierde información con el tiempo", "Varios codones distintos pueden codificar el mismo aminoácido", "Que un codón puede codificar varios aminoácidos", "Que solo funciona en algunas células"],
    {
      "Que pierde información con el tiempo": "'Degenerado' aquí es un término técnico, no indica deterioro.",
      "Que un codón puede codificar varios aminoácidos": "Sería ambigüedad, y el código no es ambiguo: cada codón especifica uno solo.",
      "Que solo funciona en algunas células": "El código es prácticamente universal.",
    }, 3),
  b("b5-5", "tema-5-acidos-nucleicos", "multi-select",
    "¿Cuáles de estas moléculas son nucleótidos o los contienen?",
    ["ATP", "NAD⁺", "FAD"],
    "Las tres comparten la arquitectura de base, azúcar y fosfato, aunque su función no tenga que ver con guardar información genética.",
    ["nucleotidos"],
    ["ATP", "NAD⁺", "FAD", "Glucógeno"],
    {
      "Glucógeno": "Es un polisacárido de glucosa: ni base nitrogenada ni fosfato en su estructura.",
    }),
  b("b5-6", "tema-5-acidos-nucleicos", "choice",
    "¿Qué produce la transcripción?",
    "ARN a partir de un molde de ADN",
    "Transcribir es pasar la información al mismo idioma de bases, cambiando de soporte; traducir es el paso al idioma de los aminoácidos.",
    ["dogma-central"],
    ["ADN a partir de ADN", "ARN a partir de un molde de ADN", "Proteína a partir de ARN", "ADN a partir de ARN"],
    {
      "ADN a partir de ADN": "Eso es la replicación.",
      "Proteína a partir de ARN": "Eso es la traducción.",
      "ADN a partir de ARN": "Eso sería retrotranscripción, propia de algunos virus, no el flujo básico.",
    }, 1),

  // ───────────── TEMA 6 ─────────────
  b("b6-1", "tema-6-agua-minerales", "choice",
    "Una célula se coloca en un medio hipotónico. ¿Qué ocurre?",
    "Entra agua y la célula se hincha",
    "El agua va hacia donde hay más solutos efectivos. Si el exterior está más diluido, el interior atrae agua.",
    ["osmosis"],
    ["Sale agua y se encoge", "Entra agua y la célula se hincha", "No hay movimiento neto de agua", "Salen los solutos y entra sodio"],
    {
      "Sale agua y se encoge": "Eso ocurre en un medio hipertónico, con el exterior más concentrado.",
      "No hay movimiento neto de agua": "Eso describe un medio isotónico.",
      "Salen los solutos y entra sodio": "La ósmosis describe el movimiento del agua, no un intercambio de solutos.",
    }, 1),
  b("b6-2", "tema-6-agua-minerales", "choice",
    "La absorción de glucosa en el enterocito mediante SGLT1 es transporte activo secundario. ¿Por qué 'secundario'?",
    "Porque no gasta ATP directamente: aprovecha el gradiente de sodio creado por la bomba",
    "El ATP se gastó antes, en la Na⁺/K⁺-ATPasa. El cotransportador solo cobra la energía almacenada en ese gradiente.",
    ["transporte"],
    ["Porque es menos importante que otros transportes", "Porque no gasta ATP directamente: aprovecha el gradiente de sodio creado por la bomba", "Porque ocurre después de comer", "Porque transporta dos glucosas a la vez"],
    {
      "Porque es menos importante que otros transportes": "'Secundario' describe el mecanismo energético, no su relevancia.",
      "Porque ocurre después de comer": "El momento no tiene que ver con la clasificación del transporte.",
      "Porque transporta dos glucosas a la vez": "Cotransporta sodio junto con glucosa, no dos glucosas.",
    }, 3),
  b("b6-3", "tema-6-agua-minerales", "short",
    "¿Cuántos K⁺ introduce la Na⁺/K⁺-ATPasa por cada ciclo?",
    "2",
    "Saca 3 Na⁺ e introduce 2 K⁺, consumiendo un ATP en el proceso.",
    ["bomba"], undefined, undefined, 1,
    "Recuerda la pareja de números: salen tres, entran dos."),
  b("b6-4", "tema-6-agua-minerales", "multi-select",
    "¿Qué factores dificultan la absorción del hierro no hemo en esa misma comida?",
    ["Fitatos", "Taninos del té o el café", "Cantidades altas de calcio"],
    "Todos ellos reducen la disponibilidad del hierro no hemo. Lo práctico es separarlos de la comida rica en hierro cuando hay riesgo de déficit.",
    ["hierro"],
    ["Fitatos", "Taninos del té o el café", "Cantidades altas de calcio", "Vitamina C"],
    {
      "Vitamina C": "Justo al contrario: el ascorbato mejora la absorción del hierro no hemo.",
    }),
  b("b6-5", "tema-6-agua-minerales", "choice",
    "¿Por qué el magnesio aparece constantemente en el metabolismo energético?",
    "Porque estabiliza el ATP, que funciona como complejo Mg-ATP",
    "El ATP en la célula está prácticamente siempre asociado a magnesio, y además el Mg²⁺ es cofactor de cientos de enzimas.",
    ["minerales"],
    ["Porque aporta calorías", "Porque estabiliza el ATP, que funciona como complejo Mg-ATP", "Porque forma parte de la hemoglobina", "Porque es el catión extracelular principal"],
    {
      "Porque aporta calorías": "Los minerales no aportan energía.",
      "Porque forma parte de la hemoglobina": "Ese es el hierro.",
      "Porque es el catión extracelular principal": "Ese es el sodio.",
    }),
  b("b6-6", "tema-6-agua-minerales", "choice",
    "Tras vómitos y diarrea intensos, ¿por qué no basta con reponer agua sola?",
    "Porque también se pierden electrolitos y cambia la osmolaridad del medio interno",
    "Reponer solo agua puede diluir aún más el medio interno. La reposición debe considerar volumen, sodio y potasio.",
    ["hidratacion"],
    ["Porque el agua no se absorbe sin comida", "Porque también se pierden electrolitos y cambia la osmolaridad del medio interno", "Porque el agua sola causa diarrea", "Porque hay que reponer primero las grasas"],
    {
      "Porque el agua no se absorbe sin comida": "El agua se absorbe, y de hecho su absorción sigue a la de solutos como el sodio.",
      "Porque el agua sola causa diarrea": "El agua no es la causa; el problema es el desequilibrio de electrolitos.",
      "Porque hay que reponer primero las grasas": "Las grasas no son la prioridad en una reposición hidroelectrolítica.",
    }, 3),
  // ───────────── TEMA 7 ─────────────
  b("b7-1", "tema-7-vitaminas", "choice",
    "Una persona con malabsorción grave de grasa tiene riesgo de déficit de...",
    "Vitaminas A, D, E y K",
    "Las liposolubles necesitan micelas y sales biliares para absorberse: si falla la absorción de grasa, fallan ellas primero.",
    ["clasificacion-vitaminas"],
    ["Vitaminas del grupo B", "Vitaminas A, D, E y K", "Vitamina C", "Todas por igual"],
    {
      "Vitaminas del grupo B": "Son hidrosolubles: se absorben con el medio acuoso y no dependen de la digestión de grasa.",
      "Vitamina C": "También es hidrosoluble.",
      "Todas por igual": "La solubilidad marca justo la diferencia entre unas y otras.",
    }),
  b("b7-2", "tema-7-vitaminas", "choice",
    "¿Por qué es peligroso tratar una anemia megaloblástica solo con folato?",
    "Porque si la causa era déficit de B12, mejora la sangre pero avanza el daño neurológico",
    "El folato corrige la alteración hematológica sin cubrir las funciones neurológicas propias de la B12, y eso puede enmascarar el cuadro.",
    ["b12"],
    ["Porque el folato es tóxico", "Porque si la causa era déficit de B12, mejora la sangre pero avanza el daño neurológico", "Porque el folato bloquea la absorción del hierro", "Porque el folato solo funciona con vitamina C"],
    {
      "Porque el folato es tóxico": "No es una cuestión de toxicidad, sino de enmascarar la causa real.",
      "Porque el folato bloquea la absorción del hierro": "No es ese el mecanismo del problema.",
      "Porque el folato solo funciona con vitamina C": "La vitamina C interviene en la absorción del hierro, no en la función del folato.",
    }, 3),
  b("b7-3", "tema-7-vitaminas", "choice",
    "¿De qué vitamina deriva el piridoxal fosfato (PLP), coenzima de las aminotransferasas?",
    "B6",
    "El PLP es imprescindible para transaminar, así que un déficit de B6 afecta al metabolismo de los aminoácidos en bloque.",
    ["coenzimas"],
    ["B1", "B6", "B12", "B2"],
    {
      "B1": "La tiamina origina el TPP, necesario en descarboxilaciones como la del piruvato.",
      "B12": "Participa en transferencias de un carbono, no como PLP.",
      "B2": "La riboflavina origina FMN y FAD.",
    }),
  b("b7-4", "tema-7-vitaminas", "choice",
    "¿Qué hace realmente la vitamina K en la coagulación?",
    "Es cofactor de una modificación que vuelve funcionales a ciertos factores",
    "No forma el coágulo ni sustituye a la cascada: permite que unas proteínas concretas maduren para poder participar después.",
    ["vitaminas-liposolubles"],
    ["Forma directamente el coágulo", "Es cofactor de una modificación que vuelve funcionales a ciertos factores", "Sustituye al calcio en la cascada", "Impide la coagulación"],
    {
      "Forma directamente el coágulo": "El coágulo lo forma la red de fibrina, al final de la cascada.",
      "Sustituye al calcio en la cascada": "El calcio tiene su propio papel y la vitamina K no lo reemplaza.",
      "Impide la coagulación": "Eso lo hacen los anticoagulantes, precisamente interfiriendo con la vitamina K.",
    }, 3),
  b("b7-5", "tema-7-vitaminas", "choice",
    "¿Por qué el déficit de vitamina C produce a la vez sangrado de encías y mala cicatrización?",
    "Porque ambas dependen de un colágeno bien hidroxilado",
    "Una sola alteración bioquímica —la hidroxilación deficiente del colágeno— se manifiesta en todos los tejidos que dependen de él.",
    ["vitamina-c"],
    ["Porque son dos enfermedades distintas que coinciden", "Porque ambas dependen de un colágeno bien hidroxilado", "Porque falta hierro en los dos casos", "Porque la vitamina C forma parte de la sangre"],
    {
      "Porque son dos enfermedades distintas que coinciden": "Es el mismo mecanismo visto en dos tejidos, no una coincidencia.",
      "Porque falta hierro en los dos casos": "La vitamina C ayuda a absorber hierro, pero estos signos vienen del colágeno.",
      "Porque la vitamina C forma parte de la sangre": "No es un componente estructural de la sangre.",
    }),
  b("b7-6", "tema-7-vitaminas", "multi-select",
    "¿Qué datos necesita una recomendación de ingesta para ser interpretable?",
    ["El grupo de población", "La unidad", "El organismo que la publica", "El año"],
    "Una cifra suelta no dice a quién se aplica ni si es una ingesta recomendada o un límite superior.",
    ["referencias"],
    ["El grupo de población", "La unidad", "El organismo que la publica", "El año", "La marca del alimento"],
    {
      "La marca del alimento": "Lo relevante es la composición y la ración, no la marca comercial.",
    }),

  // ───────────── TEMA 8 ─────────────
  b("b8-1", "tema-8-metabolismo", "choice",
    "¿Por qué los electrones que llegan por FAD rinden menos ATP que los del NADH?",
    "Porque entran a la cadena por debajo del complejo I y provocan menos bombeo de protones",
    "Llegan directamente a la ubiquinona —por el complejo II o por ETF/ETFDH—, saltándose un punto de bombeo.",
    ["fadh2"],
    ["Porque tienen menos electrones", "Porque entran a la cadena por debajo del complejo I y provocan menos bombeo de protones", "Porque se usan en el núcleo", "Porque el FAD no es una coenzima"],
    {
      "Porque tienen menos electrones": "Ambos transportadores ceden dos electrones.",
      "Porque se usan en el núcleo": "La cadena respiratoria está en la membrana mitocondrial interna.",
      "Porque el FAD no es una coenzima": "Sí lo es, y deriva de la vitamina B2.",
    }, 3),
  b("b8-2", "tema-8-metabolismo", "short",
    "¿Cuántos ATP se estiman por cada NADH mitocondrial con los valores actuales?",
    "2,5",
    "El valor moderno es aproximadamente 2,5 ATP. La cifra antigua de 3 está superada.",
    ["nadh"], undefined, undefined, 1,
    "No es un número entero."),
  b("b8-3", "tema-8-metabolismo", "choice",
    "¿Qué significa que el ATP sea 'moneda' y no 'almacén' de energía?",
    "Que la célula guarda poco y lo recicla continuamente entre ATP y ADP",
    "La reserva de ATP es muy pequeña: se regenera sin parar. El almacenamiento a largo plazo lo hacen el glucógeno y la grasa.",
    ["atp"],
    ["Que la célula guarda poco y lo recicla continuamente entre ATP y ADP", "Que el ATP se acumula en el hígado", "Que el ATP no contiene energía", "Que solo se usa en el músculo"],
    {
      "Que el ATP se acumula en el hígado": "El hígado almacena glucógeno y grasa, no depósitos de ATP.",
      "Que el ATP no contiene energía": "Sí la transfiere; lo que no hace es servir de depósito duradero.",
      "Que solo se usa en el músculo": "Lo usan todas las células.",
    }),
  b("b8-4", "tema-8-metabolismo", "choice",
    "¿Por qué la β-oxidación y la síntesis de ácidos grasos no son la misma ruta en sentidos opuestos?",
    "Usan enzimas distintas, ocurren en compartimentos distintos y se regulan por separado",
    "Esa separación permite activar una y frenar la otra, en lugar de que ambas funcionen a la vez anulándose.",
    ["rutas"],
    ["Usan enzimas distintas, ocurren en compartimentos distintos y se regulan por separado", "Porque una usa carbono y la otra no", "Porque la síntesis no consume energía", "Porque la β-oxidación ocurre en el núcleo"],
    {
      "Porque una usa carbono y la otra no": "Las dos manejan cadenas carbonadas.",
      "Porque la síntesis no consume energía": "Sí consume: ATP y NADPH.",
      "Porque la β-oxidación ocurre en el núcleo": "Ocurre en la matriz mitocondrial.",
    }, 3),
  b("b8-5", "tema-8-metabolismo", "choice",
    "¿Cuál es la diferencia entre NADH y NADPH?",
    "El NADH alimenta la producción de ATP; el NADPH aporta poder reductor para biosíntesis y defensa antioxidante",
    "Son químicamente parecidos pero la célula los mantiene en estados distintos para poder usarlos con fines diferentes.",
    ["redox"],
    ["Son la misma molécula", "El NADH alimenta la producción de ATP; el NADPH aporta poder reductor para biosíntesis y defensa antioxidante", "El NADPH produce más ATP", "El NADH solo actúa en el citosol"],
    {
      "Son la misma molécula": "Se diferencian por un grupo fosfato, y ese detalle basta para separarlos funcionalmente.",
      "El NADPH produce más ATP": "El NADPH no se usa para fabricar ATP.",
      "El NADH solo actúa en el citosol": "Se genera en ambos compartimentos y su destino principal es mitocondrial.",
    }, 3),
  b("b8-6", "tema-8-metabolismo", "choice",
    "En ayuno nocturno, ¿qué órgano sostiene la glucemia del resto del cuerpo?",
    "El hígado",
    "Solo el hígado puede liberar glucosa libre a la sangre, primero desde el glucógeno y después fabricándola.",
    ["ayuno"],
    ["El músculo", "El hígado", "El tejido adiposo", "El eritrocito"],
    {
      "El músculo": "Consume su propio glucógeno pero no puede exportar glucosa a la sangre.",
      "El tejido adiposo": "Libera ácidos grasos y glicerol, no glucosa.",
      "El eritrocito": "Consume glucosa; no la produce.",
    }, 1),

  // ───────────── TEMA 9 ─────────────
  b("b9-1", "tema-9-digestion", "choice",
    "¿Por qué el páncreas secreta tripsinógeno en lugar de tripsina activa?",
    "Para no digerirse a sí mismo: la activación ocurre ya en el intestino",
    "Un zimógeno es una enzima apagada. Se enciende en el lugar donde debe trabajar, y así el órgano que la fabrica queda protegido.",
    ["proteasas"],
    ["Porque la tripsina no cabe en el conducto", "Para no digerirse a sí mismo: la activación ocurre ya en el intestino", "Porque el tripsinógeno digiere mejor", "Porque necesita luz solar para activarse"],
    {
      "Porque la tripsina no cabe en el conducto": "El tamaño no es el problema.",
      "Porque el tripsinógeno digiere mejor": "El zimógeno es inactivo: no digiere nada hasta activarse.",
      "Porque necesita luz solar para activarse": "La activación es enzimática, por la enteropeptidasa intestinal.",
    }),
  b("b9-2", "tema-9-digestion", "choice",
    "¿Cuál es el producto principal de la acción de la lipasa pancreática sobre un triacilglicérido?",
    "2-monoacilglicérido y dos ácidos grasos libres",
    "La lipasa actúa preferentemente en las posiciones 1 y 3, dejando el tercer ácido graso unido en la posición central.",
    ["lipasa"],
    ["Glicerol y tres ácidos grasos", "2-monoacilglicérido y dos ácidos grasos libres", "Colesterol y ácidos grasos", "Glucosa y ácidos grasos"],
    {
      "Glicerol y tres ácidos grasos": "Es la versión simplificada de muchos libros, pero no describe lo que ocurre realmente.",
      "Colesterol y ácidos grasos": "El colesterol no procede de la hidrólisis de un triglicérido.",
      "Glucosa y ácidos grasos": "De una grasa no sale glucosa.",
    }, 3),
  b("b9-3", "tema-9-digestion", "choice",
    "¿Por qué un suero de rehidratación combina sodio y glucosa?",
    "Porque el SGLT1 los cotransporta, y al absorber solutos el agua sigue detrás",
    "El azúcar no está ahí para dar energía: abre la puerta al sodio, y con el sodio entra el agua.",
    ["transporte"],
    ["Porque la glucosa da energía inmediata", "Porque el SGLT1 los cotransporta, y al absorber solutos el agua sigue detrás", "Porque mejora el sabor", "Porque el sodio digiere la glucosa"],
    {
      "Porque la glucosa da energía inmediata": "El aporte calórico de un suero es mínimo y no es su objetivo.",
      "Porque mejora el sabor": "Puede ayudar a tolerarlo, pero no es el fundamento fisiológico.",
      "Porque el sodio digiere la glucosa": "El sodio no digiere nada; se cotransporta con ella.",
    }, 3),
  b("b9-4", "tema-9-digestion", "choice",
    "Un quilomicrón sale del enterocito. ¿Por dónde viaja primero?",
    "Por la linfa",
    "Es demasiado grande para entrar en un capilar sanguíneo, así que pasa al quilífero linfático y llega a la sangre más tarde.",
    ["quilomicron"],
    ["Por la vena porta", "Por la linfa", "Por el conducto biliar", "Por el estómago"],
    {
      "Por la vena porta": "Esa es la vía de los monosacáridos y aminoácidos, que sí son hidrosolubles.",
      "Por el conducto biliar": "La bilis va en sentido contrario, hacia el intestino.",
      "Por el estómago": "La absorción de nutrientes ocurre sobre todo en el intestino delgado.",
    }, 1),
  b("b9-5", "tema-9-digestion", "choice",
    "¿Qué hacen exactamente las sales biliares?",
    "Emulsionan la grasa, aumentando la superficie para que actúe la lipasa",
    "No son enzimas y no rompen ningún enlace: preparan el terreno dividiendo las gotas grandes en gotitas.",
    ["bilis"],
    ["Hidrolizan los triglicéridos", "Emulsionan la grasa, aumentando la superficie para que actúe la lipasa", "Absorben la grasa directamente", "Neutralizan las proteínas"],
    {
      "Hidrolizan los triglicéridos": "Eso lo hace la lipasa pancreática; la bilis no contiene enzimas lipolíticas.",
      "Absorben la grasa directamente": "La absorción la realiza el enterocito.",
      "Neutralizan las proteínas": "No actúan sobre las proteínas.",
    }),
  b("b9-6", "tema-9-digestion", "choice",
    "¿Qué produce la microbiota del colon al fermentar la fibra?",
    "Ácidos grasos de cadena corta como el butirato",
    "El butirato es el combustible preferente de los colonocitos: parte de la fibra acaba alimentando a tu propio intestino.",
    ["microbiota"],
    ["Glucosa que se absorbe en el colon", "Ácidos grasos de cadena corta como el butirato", "Aminoácidos esenciales", "Vitaminas liposolubles"],
    {
      "Glucosa que se absorbe en el colon": "La absorción de monosacáridos ocurre en el intestino delgado.",
      "Aminoácidos esenciales": "La microbiota no cubre las necesidades de aminoácidos indispensables.",
      "Vitaminas liposolubles": "Algunas bacterias producen vitamina K, pero el producto característico de la fermentación de fibra son los AGCC.",
    }, 3),

  // ───────────── TEMA 10 ─────────────
  b("b10-1", "tema-10-metabolismo-hc", "choice",
    "¿Por qué fosforilar la glucosa a glucosa-6-fosfato la retiene dentro de la célula?",
    "Porque los transportadores GLUT reconocen glucosa, no glucosa-6-fosfato",
    "Al añadir el fosfato, la molécula deja de encajar en el transportador por el que entró y ya no puede salir.",
    ["glucolisis"],
    ["Porque se vuelve más pesada", "Porque los transportadores GLUT reconocen glucosa, no glucosa-6-fosfato", "Porque la membrana se cierra", "Porque el fosfato la disuelve"],
    {
      "Porque se vuelve más pesada": "El peso no es lo que impide el paso: es el reconocimiento por el transportador.",
      "Porque la membrana se cierra": "La membrana no cambia; lo que cambia es la molécula.",
      "Porque el fosfato la disuelve": "La glucosa ya era soluble.",
    }, 3),
  b("b10-2", "tema-10-metabolismo-hc", "choice",
    "¿Qué produce la vía de las pentosas fosfato que no produce la glucólisis?",
    "NADPH y ribosa-5-fosfato",
    "No genera ATP. Aporta poder reductor para biosíntesis y defensa antioxidante, y el azúcar de los nucleótidos.",
    ["pentosas-fosfato"],
    ["Más ATP que la glucólisis", "NADPH y ribosa-5-fosfato", "Lactato y CO₂", "Cuerpos cetónicos"],
    {
      "Más ATP que la glucólisis": "No es una ruta productora de ATP.",
      "Lactato y CO₂": "El lactato procede del piruvato; no es producto característico de esta vía.",
      "Cuerpos cetónicos": "Se forman en el hígado desde acetil-CoA, en otra ruta.",
    }, 3),
  b("b10-3", "tema-10-metabolismo-hc", "choice",
    "¿Por qué el músculo no puede aportar glucosa libre a la sangre desde su glucógeno?",
    "Porque carece de glucosa-6-fosfatasa",
    "Sin esa enzima no puede retirar el fosfato, y la glucosa-6-fosfato no atraviesa la membrana.",
    ["glucogeno"],
    ["Porque su glucógeno tiene enlaces β", "Porque carece de glucosa-6-fosfatasa", "Porque no tiene mitocondrias", "Porque la insulina se lo impide"],
    {
      "Porque su glucógeno tiene enlaces β": "El glucógeno usa enlaces α, tanto en hígado como en músculo.",
      "Porque no tiene mitocondrias": "El músculo tiene muchas mitocondrias; el eritrocito es el que no las tiene.",
      "Porque la insulina se lo impide": "Es una limitación enzimática permanente, no hormonal.",
    }),
  b("b10-4", "tema-10-metabolismo-hc", "choice",
    "El eritrocito produce lactato incluso con oxígeno disponible. ¿Por qué?",
    "Porque no tiene mitocondrias y necesita regenerar NAD⁺ para seguir con la glucólisis",
    "El lactato no indica falta de oxígeno: indica necesidad de reoxidar NADH cuando no hay otra vía disponible.",
    ["lactato"],
    ["Porque le falta oxígeno en la sangre", "Porque no tiene mitocondrias y necesita regenerar NAD⁺ para seguir con la glucólisis", "Porque el lactato es un desecho tóxico", "Porque consume grasas"],
    {
      "Porque le falta oxígeno en la sangre": "El eritrocito viaja precisamente cargado de oxígeno.",
      "Porque el lactato es un desecho tóxico": "El lactato es un metabolito reutilizable que otros tejidos consumen.",
      "Porque consume grasas": "El eritrocito depende de la glucosa.",
    }, 3),
  b("b10-5", "tema-10-metabolismo-hc", "multi-select",
    "¿Qué produce una vuelta del ciclo de Krebs por cada acetil-CoA?",
    ["3 NADH", "1 FADH₂", "1 GTP", "2 CO₂"],
    "Ese es el balance por acetil-CoA. Una glucosa provoca dos vueltas, así que hay que duplicarlo.",
    ["krebs"],
    ["3 NADH", "1 FADH₂", "1 GTP", "2 CO₂", "2 ATP directos"],
    {
      "2 ATP directos": "El ciclo produce GTP por fosforilación a nivel de sustrato, no ATP directo.",
    }),
  b("b10-6", "tema-10-metabolismo-hc", "choice",
    "¿Por qué el rendimiento de una glucosa se expresa como 30–32 ATP y no con una cifra exacta?",
    "Porque depende de la lanzadera usada para los NADH citosólicos y el acoplamiento no da enteros",
    "Los NADH de la glucólisis no cruzan la membrana interna: sus electrones entran por lanzaderas de rendimiento distinto.",
    ["rendimiento"],
    ["Porque los libros no se ponen de acuerdo", "Porque depende de la lanzadera usada para los NADH citosólicos y el acoplamiento no da enteros", "Porque depende de lo que hayas comido", "Porque el oxígeno varía"],
    {
      "Porque los libros no se ponen de acuerdo": "El intervalo tiene una razón bioquímica concreta, no editorial.",
      "Porque depende de lo que hayas comido": "El rendimiento por molécula no cambia con la dieta.",
      "Porque el oxígeno varía": "El aceptor final es el mismo; el margen viene de las lanzaderas y el acoplamiento.",
    }, 3),
  b("b10-7", "tema-10-metabolismo-hc", "multi-select",
    "¿Cuáles pueden aportar carbono neto para fabricar glucosa?",
    ["Lactato", "Glicerol", "Alanina"],
    "Los tres entran por encima del paso irreversible piruvato → acetil-CoA, así que pueden dar glucosa.",
    ["gluconeogenesis"],
    ["Lactato", "Glicerol", "Alanina", "Acetil-CoA del palmitato"],
    {
      "Acetil-CoA del palmitato": "El paso piruvato → acetil-CoA es irreversible en humanos: por eso la grasa de cadena par no da glucosa de forma neta.",
    }, 3),

  // ───────────── TEMA 11 ─────────────
  b("b11-1", "tema-11-metabolismo-lipidico", "short",
    "¿Cuántos acetil-CoA se obtienen de la β-oxidación completa del palmitato (C16:0)?",
    "8",
    "Para una cadena par de n carbonos, los acetil-CoA son n/2. Aquí, 16/2 = 8.",
    ["beta-oxidacion"], undefined, undefined, 2,
    "Divide el número de carbonos entre dos."),
  b("b11-2", "tema-11-metabolismo-lipidico", "choice",
    "¿Por qué hay un ciclo menos de β-oxidación que acetil-CoA producidos?",
    "Porque el último corte parte una cadena de cuatro carbonos en dos acetil-CoA de golpe",
    "Los ciclos anteriores liberan uno cada vez; el final libera dos, y por eso ciclos = n/2 − 1.",
    ["beta-oxidacion"],
    ["Porque el primer ciclo no cuenta", "Porque el último corte parte una cadena de cuatro carbonos en dos acetil-CoA de golpe", "Porque uno se pierde como CO₂", "Porque la activación consume uno"],
    {
      "Porque el primer ciclo no cuenta": "Todos los ciclos cuentan; la particularidad está al final.",
      "Porque uno se pierde como CO₂": "En la β-oxidación no se libera CO₂; eso ocurre después, en Krebs.",
      "Porque la activación consume uno": "La activación cuesta ATP, no acetil-CoA.",
    }, 3),
  b("b11-3", "tema-11-metabolismo-lipidico", "choice",
    "¿Por qué el hígado fabrica cuerpos cetónicos pero no los utiliza?",
    "Porque carece de la enzima SCOT (OXCT1) necesaria para activarlos",
    "Sin SCOT no hay cetólisis hepática: el hígado produce combustible para músculo, corazón, riñón y cerebro adaptado.",
    ["cetonas"],
    ["Porque no tiene mitocondrias", "Porque carece de la enzima SCOT (OXCT1) necesaria para activarlos", "Porque los cuerpos cetónicos son tóxicos para el hígado", "Porque prefiere la glucosa"],
    {
      "Porque no tiene mitocondrias": "El hígado tiene abundantes mitocondrias; es donde ocurre la cetogénesis.",
      "Porque los cuerpos cetónicos son tóxicos para el hígado": "No es una cuestión de toxicidad, sino de que le falta una enzima.",
      "Porque prefiere la glucosa": "En ayuno el hígado no está consumiendo glucosa: la está fabricando.",
    }, 3),
  b("b11-4", "tema-11-metabolismo-lipidico", "choice",
    "¿Qué inhibe la CPT-I e impide oxidar grasa mientras se está sintetizando?",
    "El malonil-CoA",
    "Es el primer intermediario de la síntesis: si hay malonil-CoA, la puerta de entrada a la mitocondria se cierra y se evita un ciclo fútil.",
    ["regulacion-lipidica"],
    ["La carnitina", "El malonil-CoA", "El glicerol", "La albúmina"],
    {
      "La carnitina": "Al contrario: la carnitina es la que transporta el acilo hacia dentro.",
      "El glicerol": "Se libera en la lipólisis y va sobre todo al hígado; no regula la CPT-I.",
      "La albúmina": "Transporta ácidos grasos por el plasma; no actúa dentro de la célula.",
    }, 3),
  b("b11-5", "tema-11-metabolismo-lipidico", "choice",
    "¿Cuál es la diferencia entre cetosis fisiológica y cetoacidosis?",
    "En la cetosis el pH se mantiene; en la cetoacidosis la producción se dispara y el tampón se ve superado",
    "Comparten nombre pero no gravedad: la cetoacidosis requiere un déficit grave de insulina y es una urgencia médica.",
    ["cetonas"],
    ["Son lo mismo con distinto nombre", "En la cetosis el pH se mantiene; en la cetoacidosis la producción se dispara y el tampón se ve superado", "La cetosis es más grave", "La cetoacidosis solo ocurre en ayuno"],
    {
      "Son lo mismo con distinto nombre": "Es justo la confusión que hay que evitar en consulta.",
      "La cetosis es más grave": "Es al revés.",
      "La cetoacidosis solo ocurre en ayuno": "Se asocia sobre todo a déficit grave de insulina, como en la diabetes tipo 1.",
    }, 3),
  b("b11-6", "tema-11-metabolismo-lipidico", "choice",
    "¿Cómo se convierte una VLDL en LDL?",
    "Perdiendo triglicéridos por acción de la LPL, quedando relativamente rica en colesterol",
    "Las lipoproteínas se remodelan en circulación: la LDL no se secreta como tal, se forma por el camino.",
    ["lipoproteinas"],
    ["El hígado la secreta ya como LDL", "Perdiendo triglicéridos por acción de la LPL, quedando relativamente rica en colesterol", "Ganando triglicéridos en los tejidos", "Uniéndose a una HDL"],
    {
      "El hígado la secreta ya como LDL": "El hígado secreta VLDL; la LDL aparece después.",
      "Ganando triglicéridos en los tejidos": "Los pierde, no los gana: la LPL los retira.",
      "Uniéndose a una HDL": "Las HDL participan en el transporte de retorno, no en formar LDL por fusión.",
    }, 3),

  // ───────────── TEMA 12 ─────────────
  b("b12-1", "tema-12-metabolismo-proteico", "choice",
    "¿Qué ocurre en una transaminación?",
    "Un aminoácido cede su grupo amino a un α-cetoácido, sin liberar amonio",
    "El nitrógeno cambia de portador. Para soltarlo como amonio hace falta una desaminación, que es otra reacción.",
    ["transaminacion"],
    ["Se libera amonio directamente", "Un aminoácido cede su grupo amino a un α-cetoácido, sin liberar amonio", "Se rompe un enlace peptídico", "Se forma urea"],
    {
      "Se libera amonio directamente": "Eso corresponde a la desaminación oxidativa del glutamato.",
      "Se rompe un enlace peptídico": "Eso es hidrólisis, propia de las proteasas.",
      "Se forma urea": "La urea se forma después, en el ciclo hepático.",
    }),
  b("b12-2", "tema-12-metabolismo-proteico", "choice",
    "¿En qué órgano se sintetiza la urea y cuál la elimina?",
    "Se sintetiza en el hígado y la elimina el riñón",
    "Es un error clásico atribuir la síntesis al riñón: el riñón solo la excreta.",
    ["urea"],
    ["Se sintetiza en el riñón y la elimina el hígado", "Se sintetiza en el hígado y la elimina el riñón", "Ambas cosas en el riñón", "Ambas cosas en el intestino"],
    {
      "Se sintetiza en el riñón y la elimina el hígado": "Están intercambiados.",
      "Ambas cosas en el riñón": "El ciclo de la urea es hepático.",
      "Ambas cosas en el intestino": "El intestino no participa en el ciclo de la urea.",
    }, 1),
  b("b12-3", "tema-12-metabolismo-proteico", "multi-select",
    "¿De dónde proceden los dos nitrógenos de la urea?",
    ["Del amonio, vía carbamoil fosfato", "Del aspartato"],
    "Cada nitrógeno entra por una puerta distinta, y el carbono procede del bicarbonato.",
    ["urea"],
    ["Del amonio, vía carbamoil fosfato", "Del aspartato", "De la glucosa", "De un ácido graso"],
    {
      "De la glucosa": "La glucosa no contiene nitrógeno.",
      "De un ácido graso": "Los ácidos grasos tampoco contienen nitrógeno.",
    }, 3),
  b("b12-4", "tema-12-metabolismo-proteico", "choice",
    "¿Qué aminoácidos son exclusivamente cetogénicos?",
    "Leucina y lisina",
    "Solo esos dos. La mayoría son glucogénicos o mixtos, y por eso la excepción es lo que se pregunta.",
    ["destino-carbono"],
    ["Alanina y glutamato", "Leucina y lisina", "Serina y glicina", "Todos los esenciales"],
    {
      "Alanina y glutamato": "Ambos son glucogénicos: dan piruvato y α-cetoglutarato.",
      "Serina y glicina": "También son glucogénicos.",
      "Todos los esenciales": "Ser esencial es una etiqueta nutricional, sin relación con el destino del carbono.",
    }, 3),
  b("b12-5", "tema-12-metabolismo-proteico", "choice",
    "¿Por qué no existe un 'almacén de proteína' equivalente al glucógeno?",
    "Porque toda la proteína corporal es funcional: no hay depósito de reserva dedicado",
    "Cuando falta energía, el cuerpo degrada estructura en uso, no una reserva inocua guardada para eso.",
    ["balance-nitrogenado"],
    ["Porque la proteína no se puede almacenar químicamente", "Porque toda la proteína corporal es funcional: no hay depósito de reserva dedicado", "Porque el hígado la destruye enseguida", "Porque se elimina toda por la orina"],
    {
      "Porque la proteína no se puede almacenar químicamente": "El problema no es químico: existe proteína corporal, pero toda cumple una función.",
      "Porque el hígado la destruye enseguida": "El hígado regula el recambio, no destruye toda la proteína ingerida.",
      "Porque se elimina toda por la orina": "Lo que se elimina es el nitrógeno como urea, no la proteína entera.",
    }, 3),
  b("b12-6", "tema-12-metabolismo-proteico", "choice",
    "Un paciente recibe proteína suficiente pero poca energía. ¿Por qué empeora su balance nitrogenado?",
    "Porque los aminoácidos se usan como combustible en lugar de para sintetizar",
    "Sin energía suficiente, la proteína arde en vez de construir. Por eso el soporte nutricional cubre primero la energía.",
    ["balance-nitrogenado"],
    ["Porque la proteína no se absorbe sin grasa", "Porque los aminoácidos se usan como combustible en lugar de para sintetizar", "Porque el exceso de proteína daña el riñón", "Porque se pierde nitrógeno por las heces"],
    {
      "Porque la proteína no se absorbe sin grasa": "La absorción de aminoácidos no depende de la grasa.",
      "Porque el exceso de proteína daña el riñón": "El problema aquí es el defecto de energía, no un exceso proteico.",
      "Porque se pierde nitrógeno por las heces": "La vía principal de pérdida es la urea urinaria.",
    }, 3),
];

